// The 24 cards of The Console.
// Each card describes a recognizable life situation named with a tech metaphor.
// The deck is flat (no categories or suits). Ids are 1-24.
export const cards = [
    {
        id: 1,
        name: 'Handshake',
        type: 'connection',
        brief: 'Setup is complete and you are ready for action.',
        tech: 'A handshake is the exchange that two systems use to establish a working connection. Once it completes, the actual work can begin.',
        situation: 'A new agreement is in place between two parties.',
        examples: [
            'Starting a new job',
            'Making a relationship official',
            'Signing a contract',
            'Beginning a mentorship',
            'Joining a team',
            'Agreeing to a treatment plan',
            'Initiating a creative collaboration',
        ],
        reflection: 'A handshake is the multi-step exchange by which two systems confirm they can communicate and on what terms. Each side signals readiness, and the protocol completes only when both confirm. From this point forward, both are bound to what was agreed. The terms shape everything that follows, even when no one is tracking them anymore. The visible part of a handshake is the connection. The lasting part is the terms.',
    },
    {
        id: 2,
        name: 'Connection Refused',
        type: 'connection',
        brief: 'You got an answer, and the answer was no.',
        tech: 'Connection Refused is a specific TCP error. The rejection is clear, immediate, and definitive.',
        situation: 'A direct, unambiguous no.',
        examples: [
            'A job application denied',
            'An invitation declined',
            'A breakup',
            'A block on social media',
            'A rejection from a romantic interest',
        ],
        reflection: 'Connection Refused is the case where the destination is reachable and responsive but actively rejects the request. The rejection itself is a signal. The system is functioning and the answer has been delivered. Unlike silence or unreachability, the situation contains no ambiguity. A clear refusal closes a possibility with certainty, which is often more useful than a maybe.',
    },
    {
        id: 3,
        name: 'Timeout',
        type: 'time',
        brief: 'You waited for a response, but it never arrived.',
        tech: 'A timeout is when a system gives up waiting for a response. After a configured time, the request is treated as failed.',
        situation: 'Silence where an answer was expected.',
        examples: [
            'A job application that goes unanswered',
            'A date request that gets ignored',
            'A friendship that fades away',
            'A promise that never gets fulfilled',
            'An apology that never comes',
        ],
        reflection: 'A timeout is the moment a system stops waiting for a response that never came. The request was sent, a window of time passed, and no answer arrived. The other side might never have received the message, or might have received it and chosen not to reply. From this side, both look the same. A timeout is structurally ambiguous: it only tells you that nothing came back. Choosing to time out is a choice to stop waiting. The cause of the silence may remain unknown.',
    },
    {
        id: 4,
        name: 'Loopback',
        type: 'connection',
        brief: 'You are in conversation with yourself.',
        tech: 'Loopback is when a system communicates with itself. It is often used for testing, or for two programs on the same machine to talk to each other.',
        situation: 'You are circling through something on your own.',
        examples: [
            'Rehearsing a conversation in your head',
            'Revising an unsent message',
            'Ruminating on something that happened',
            'Imagining what someone would say',
            'Wavering on a decision',
        ],
        reflection: 'A loopback routes a signal from a system back to itself. Outputs become the next inputs, and no new information enters from outside. Closed loops are sometimes deliberate, used for calibration, self-test, or internal processing. They can also serve as a stand-in for the exchange that would actually resolve the situation. From inside the loop, both versions look the same. Only outside information can tell them apart.',
    },
    {
        id: 5,
        name: 'Bridge',
        type: 'connection',
        brief: 'A bridge between two worlds.',
        tech: 'A network bridge connects two network segments so traffic flows between them. More broadly, a bridge links two systems built on different terms.',
        situation: 'You are the connection between two or more separate worlds.',
        examples: [
            'Translating between two people who think very differently',
            'Helping a partner understand your family or vice versa',
            'Explaining a job to people outside the field',
            "Mediating a conflict",
            'Connecting friends with coworkers',
        ],
        reflection: 'A bridge is the structural element that allows two systems built on different terms to interact. Each side communicates in its own form. To translate, the bridge has to hold both sets of terms at once. Neither endpoint does this. The bridge ends up knowing both forms, and the structure of what passes between them. From the middle, you see things about each side that the side cannot see about itself.',
    },
    {
        id: 6,
        name: 'Buffer Full',
        type: 'state',
        brief: "You're already at your limit, and more keeps adding pressure.",
        tech: "A buffer is temporary storage that holds data while it's moving from one place to another.",
        situation: 'Everything pressing on you at once.',
        examples: [
            'Drowning in unread messages',
            'Falling behind on a growing to-do list',
            'Juggling too many commitments at once',
            'Treating everything coming in as urgent',
            'Working on too many projects at the same time',
            'Being pulled in too many directions',
            'Running from one thing to the next without a break',
        ],
        reflection: 'The system is at capacity. Inputs are arriving faster than they can be processed, and every system at this point either drops new input, queues it indefinitely, or applies backpressure to the source. There is no fourth option. The choice is being made now, with or without your awareness or consent. That, more than the overload itself, is usually what makes the experience hard.',
    },
    {
        id: 7,
        name: 'Stale Cache',
        type: 'state',
        brief: "You're working from outdated information.",
        tech: 'A cache stores a copy of data so it can be retrieved quickly without going back to the original source.',
        situation: 'Going by what used to be true.',
        examples: [
            'Treating someone as the person they used to be',
            'Returning to a place expecting it to be unchanged',
            'Keeping an outdated self-image',
            "Not seeing that a relationship has changed",
            'Going by social rules that have since evolved',
            'Holding on to opinions you formed long ago',
        ],
        reflection: 'A cache holds a copy of data taken at some point in the past. The system reads from the cache rather than the source, which is cheaper and faster. The cache becomes stale when the source changes but the copy stays the same. From inside the system, there is no automatic signal that the cache has gone stale. The system continues operating on the snapshot, producing results that are internally consistent and externally wrong. The structural problem is the gap between when the source changed and when the system caught up. During that gap, the system runs on confidence that no longer applies.',
    },
    {
        id: 8,
        name: 'Memory Leak',
        type: 'state',
        brief: 'Something keeps quietly draining your attention.',
        tech: 'A memory leak is when a program holds onto memory past when it needs it.',
        situation: 'Something keeps pulling at you, again and again.',
        examples: [
            'A recurring worry',
            'A frequent regret',
            'An unprocessed loss',
            'A relived trauma',
            'A nagging health concern',
        ],
        reflection: 'A memory leak is when a system holds onto information past when it needs it. Each instance is small. Their accumulation, over time, becomes the structural issue. Slow leaks are difficult to detect in the moment because the system continues running and capacity decreases gradually. What gets noticed is usually the effect: the system feels heavier, slower, or less responsive, without anything specific being clearly wrong.',
    },
    {
        id: 9,
        name: 'Crash',
        type: 'state',
        brief: 'Something has suddenly stopped, and is now gone.',
        tech: 'A crash is when a system stops running suddenly because of an error that broke it.',
        situation: 'A sudden ending.',
        examples: [
            'A relationship that ended',
            'A sudden loss in the family',
            'An unexpected health crisis',
            'A job or career ending abruptly',
            'A mental or emotional breakdown',
        ],
        reflection: 'A crash is when a system stops running suddenly. State held in memory at the time of the break is lost. In computing, state written to durable storage survives, and the system can be restarted from it. In life, what is lost often cannot be restored. You move forward, changed by both what is gone and what remains.',
    },
    {
        id: 10,
        name: 'Restore',
        type: 'change',
        brief: 'Help is here, and you are coming back.',
        tech: 'A restore brings back data or system state from a backup.',
        situation: 'Being supported while you recover.',
        examples: [
            'Family stepping up during a hard time',
            'Friends showing up when you needed it the most',
            'A community rallying around you during a crisis',
            'Recovery time your body or mind needed',
            'Slowly feeling like yourself again after a challenging time',
        ],
        reflection: 'A restore brings back data or state from a saved copy. The saved state makes return possible after a failure. In computing, the recovered state is identical to what was saved. In life, recovery is rarely so clean. The experience itself changes the system that comes through it.',
    },
    {
        id: 11,
        name: 'Echo',
        type: 'connection',
        brief: 'Whatever you put out comes back to you unchanged.',
        tech: 'An echo is the return of a signal in the same form it was sent.',
        situation: 'You keep hearing what you already believe.',
        examples: [
            'Hearing the same opinions from everyone you talk to',
            'Reading news that confirms your beliefs',
            'Speaking to people who say what you want to hear',
            'Surrounding yourself with people who think just like you',
        ],
        reflection: 'An echo is the return of a signal in the same form it was sent. The system sends, the same form returns, and over time the pattern repeats. When everything that comes back matches what was sent, the loop has closed to outside input. Confirmation that arrives from a closed loop is structurally indistinguishable from no information. A system that only hears its own signal cannot detect when it has drifted from reality.',
    },
    {
        id: 12,
        name: 'Static',
        type: 'connection',
        brief: "What you're trying to hear or say is getting lost in too much noise.",
        tech: 'Static is random noise that gets mixed into a transmission and makes the actual signal hard to hear.',
        situation: 'Too much noise around what matters.',
        examples: [
            'Trying to focus while notifications keep going off',
            'Hearing yourself think in a household full of demands',
            'Having a serious conversation in a busy public place',
            'Searching for your own opinion among many strong ones',
            'Working on something important amid constant interruptions',
            "Feeling something honestly when there's too much else going on",
            'Sending a clear message in a crowded conversation',
        ],
        reflection: "Static is noise mixed into a transmission that makes the actual signal hard to hear. The signal is still present. Multiple sources contribute noise to the channel at once, and at some point the signal-to-noise ratio crosses a threshold where the message becomes inaudible. Recovery happens by reducing noise or strengthening signal. Most of the time, the message hasn't disappeared. The work is lowering the noise enough that what is already there becomes audible.",
    },
    {
        id: 13,
        name: 'Heartbeat',
        type: 'time',
        brief: 'A steady rhythm that keeps something alive.',
        tech: 'A heartbeat is a regular signal sent at fixed intervals so other systems know a process is still alive.',
        situation: 'Small steady actions that maintain something.',
        examples: [
            'Calling your parents every Sunday',
            'Going to therapy weekly even when you feel fine',
            'Doing your morning routine even on hard days',
            'Showing up to a hobby practice on schedule',
            'Tending to the basics each day (eating, sleeping, moving)',
            'Maintaining a small daily ritual that grounds you',
            'Keeping in touch with someone through brief regular messages',
        ],
        reflection: "A heartbeat is a regular signal sent at fixed intervals to indicate a system is still alive. The signal itself carries no content. Its existence is the message. Other systems listen for these signals to confirm presence, and when the signals stop, the sender is presumed failed. No single beat is definitive: the information is in the rhythm. Stability comes from the consistency of the pattern.",
    },
    {
        id: 14,
        name: 'Throttled',
        type: 'state',
        brief: "You're holding something back.",
        tech: 'Throttling is when a system intentionally limits the rate of output.',
        situation: 'Not fully sharing everything that you could.',
        examples: [
            'Hiding aspects of yourself while at work',
            'Working at a slower speed to avoid overwhelming someone',
            "Keeping back creative ideas that don't fit the project",
            'Speaking carefully to avoid conflict',
            'Editing yourself to avoid offending others',
        ],
        reflection: 'Throttling is when a system intentionally limits the rate of its output. The full capacity remains present. The constraint is structural, set somewhere in the configuration. A throttle exists for a reason: protecting downstream systems, conserving resources, meeting external rules. The constraint can outlast the conditions that produced it. A throttle that goes unexamined becomes invisible. Over time, the limit can stop being recognized as configurable. It may begin to feel like the actual edge of what is possible.',
    },
    {
        id: 15,
        name: 'Idle',
        type: 'state',
        brief: 'You have time and capacity, and nothing is required of you.',
        tech: 'Idle is when a system has capacity available with nothing currently using it.',
        situation: 'Free time with no demands.',
        examples: [
            'A vacation',
            'A free evening with no obligations',
            'A pause between projects',
            'An open Saturday afternoon',
            'Rest after hard work',
        ],
        reflection: 'Idle is when a system has capacity available with nothing currently using it. The system is fully operational, with no active demand. Capacity is present and uncalled. The state can be mistaken for malfunction by anyone who measures function by activity. Idle is the system working correctly. The discomfort comes from confusing activity with purpose.',
    },
    {
        id: 16,
        name: 'Polling',
        type: 'time',
        brief: "You keep checking for something that hasn't happened yet.",
        tech: 'Polling is when a system repeatedly checks for an update at regular intervals.',
        situation: 'Repeatedly checking while you wait.',
        examples: [
            'Reloading your inbox waiting for a reply',
            'Checking your phone repeatedly for a text',
            'Watching for news of a pending event',
            'Checking the mail for an expected package'
        ],
        reflection: 'Polling is the pattern of repeatedly checking for an update at regular intervals. Each check carries a cost, whether or not anything has changed. The pattern is necessary when there is no other way to be notified. It also serves as a substitute for being notified. When push is unavailable, pull keeps happening. Individual checks are cheap. The cumulative cost dominates. The cost of polling lives in the pattern itself. Over time, the rhythm of checking can become its own kind of anxiety.',
    },
    {
        id: 17,
        name: 'Sync',
        type: 'time',
        brief: 'Things are coming together at the right time.',
        tech: 'Sync is when two or more systems align in time so their actions happen together, or they reach the same state at once.',
        situation: 'Multiple things happening in the same moment.',
        examples: [
            'A planned event taking place',
            "A career opportunity",
            'A relationship deepening',
            'A creative project starting',
            'A health improvement',
            'An invitation',
        ],
        reflection: 'Synchronization is the alignment of multiple systems in time so their actions or states coincide. Most systems run on independent rhythms. Sync is the rare condition where those rhythms briefly come into phase. When it happens, coordinated action becomes possible that no system could produce alone.',
    },
    {
        id: 18,
        name: 'Latency',
        type: 'time',
        brief: "There's a long gap between your input and the response.",
        tech: 'Latency is the delay between when something is sent and when it arrives.',
        situation: 'Time passing between cause and effect.',
        examples: [
            "A message you sent that hasn't been answered yet",
            'A decision whose consequences are still undetermined',
            "A career move that hasn't paid off so far",
            "A new habit that hasn't changed your life yet",
            'A medical treatment that takes weeks to start working',
        ],
        reflection: 'Latency is the gap between when a signal is sent and when it arrives. During this gap, the signal is in transit. No information about the result is available until the gap closes. Latency is structurally distinct from failure. A delayed signal is still moving. It just has not arrived. The temptation during latency is to interpret what has not yet arrived. A signal in transit is not yet a result. Whatever you imagine while waiting will be overwritten by what actually arrives.',
    },
    {
        id: 19,
        name: 'Fork',
        type: 'change',
        brief: 'Two paths are opening up before you.',
        tech: 'A fork is when a single process splits into two or more separate paths.',
        situation: 'A choice between paths.',
        examples: [
            'Staying somewhere familiar or leaving for something new',
            'Committing to a relationship or keeping it casual',
            'Choosing a safe path or a risky one',
            'Applying a quick fix or spending more effort to repair something properly',
            "Caring for yourself or helping someone else",
        ],
        reflection: 'A fork splits a single process into two or more independent paths. From the fork point, each path develops on its own state and its own decisions. The past up to the fork is shared, but everything after diverges. The structural feature of a fork is that choosing produces direction. Up to the fork, all paths are possibilities. After the fork, the chosen path is the one that matters. Clarity can come from the choice itself.',
    },
    {
        id: 20,
        name: 'Deadlock',
        type: 'time',
        brief: 'Both sides are stuck, each waiting on the other to take action.',
        tech: 'A deadlock is when two or more processes are each waiting for the other to release something.',
        situation: 'Two sides waiting for the other to move first.',
        examples: [
            'After an argument, friends waiting for each other to apologize',
            'Two cars at an intersection, each waiting for the other to move first',
            'A negotiation frozen with both sides waiting for the other to budge',
            'Wanting to do something while knowing you shouldn\'t',
            'Knowing you need to change, but not allowing yourself to admit it',
        ],
        reflection: 'A deadlock is when two or more sides are each waiting for the other to release something. Each holds what the other needs. Both are blocked. No side in a deadlock is wrong. The configuration produces the freeze. The deadlock can be broken when someone becomes willing to compromise. Until that happens, nothing will change.',
    },
    {
        id: 21,
        name: 'Merge',
        type: 'change',
        brief: 'Two separate things are coming together.',
        tech: 'A merge is when two separate branches of work are combined into one.',
        situation: 'Separate streams joining.',
        examples: [
            'Reconnecting with a partner after time apart',
            'Rejoining a community you stepped away from',
            'Pulling two separate work projects into one',
            'Reconciling with a family member',
            'Becoming part of a new team or organization',
            'Combining your personal and professional lives',
        ],
        reflection: 'A merge brings two things together so they can function as one. The result includes elements from both sides. Where they fit seamlessly, integration is automatic. Where they conflict, the differences must be resolved before the merge can complete. Two things coming together rarely fit smoothly without negotiation. That negotiation is the work of merging.',
    },
    {
        id: 22,
        name: 'Garbage Collection',
        type: 'change',
        brief: 'Letting go of what is no longer needed.',
        tech: 'Garbage collection is the automatic process by which a system reclaims memory that has been used up and is ready to be released. The reclaimed space becomes available for new work.',
        situation: 'Time to clear out what is finished.',
        examples: [
            'Letting go of an old grudge',
            "Giving away clothes you haven't worn in years",
            "Walking away from a habit that no longer serves you",
            "Releasing a friendship that's run its course",
            "Donating books you've already read",
        ],
        reflection: 'Garbage collection is the process by which a system identifies and reclaims memory no longer in use. Reachability is the test: anything that can no longer be traced from somewhere active is treated as garbage. Garbage is the natural state of things that have served their purpose. The work of garbage collection is identifying what is no longer connected to anything still active. Past usefulness is irrelevant to the test. What makes something garbage is the absence of any current utility.',
    },
    {
        id: 23,
        name: 'Patch',
        type: 'change',
        brief: 'A quick fix to keep things going for now.',
        tech: 'A patch is a small, quick change made to fix a specific problem.',
        situation: 'A temporary fix to bridge the gap.',
        examples: [
            'Patching a flat tire until you can get a new one',
            'Taking medicine for symptoms while you determine the cause',
            'Negotiating a temporary work arrangement',
            'Apologizing to quickly end a conflict',
            'Borrowing money to cover an unexpected expense',
        ],
        reflection: 'A patch is a small, localized change that fixes a specific problem without changing the underlying structure. Something is malfunctioning. A targeted change is made to make the symptom go away. The system runs again. The underlying cause carries forward. Patches buy time. They also accumulate. A system covered in patches becomes harder to understand and harder to repair properly. A patch is the deferral of a repair. The time it buys can be used to design a proper fix.',
    },
    {
        id: 24,
        name: 'Reset',
        type: 'change',
        brief: 'You are starting over.',
        tech: 'A reset returns a system to its starting state.',
        situation: 'A fresh start.',
        examples: [
            'Beginning a new chapter after a major life change',
            'Picking up the pieces after a relationship has ended',
            'Rebuilding after a loss',
            'Changing jobs or careers',
            'Moving to a new home',
            'Recovering from a serious illness',
        ],
        reflection: 'A reset clears whatever has accumulated. Variables, configuration, working memory, all of it is wiped. In computing, the system returns to its original initial conditions. In life, a reset rarely returns you to who you were before. It opens into a fresh new state, starting from where you are now.',
    },
]
