// The 24 cards of The Console.
// Each card describes a recognizable life situation named with a tech metaphor.
// The deck is flat (no categories or suits). Ids are 1-24.
export const cards = [
    {
        id: 1,
        name: 'Handshake',
        brief: 'Setup is complete and you are ready for action.',
        tech: 'A handshake is the exchange that two systems use to establish a working connection. Each side confirms it can hear the other and they agree on the terms. Once it completes, the actual work can begin.',
        situation: 'A new agreement is in place between two parties.',
        examples: [
            'A new job started',
            'A relationship made official',
            'A contract signed',
            'A mentorship begun',
            'A team joined',
            'A treatment plan agreed on with a doctor',
            'A creative collaboration initiated',
        ],
        reflection: 'Take a moment to consider all of the ways this change will impact your life. Is there anything you can do to feel prepared?',
    },
    {
        id: 2,
        name: 'Connection Refused',
        brief: 'You got an answer, and the answer was no.',
        tech: 'Connection Refused is a specific TCP error. The destination is reachable and the host responds, but it actively rejects the connection. The rejection is clear, immediate, and definitive.',
        situation: 'A direct, unambiguous no.',
        examples: [
            'A job application rejected',
            'A submission turned down',
            'A pitch declined',
            'An invitation refused',
            'A breakup',
            'A hard line from a friend or partner',
            'A social media block',
            'A clear "no" from a romantic interest',
        ],
        reflection: 'What does this no tell you about yourself, the other party, or the timing? What new opportunities might arise from this apparent rejection?',
    },
    {
        id: 3,
        name: 'Timeout',
        brief: 'You waited for a response, but it never arrived.',
        tech: 'A timeout is when a system gives up waiting for a response. After a configured time, the request is treated as failed.',
        situation: 'Silence where an answer was expected.',
        examples: [
            'A job application that goes unanswered',
            'A date request that gets no reply',
            'A friendship that quietly fades',
            'A promise that never gets kept',
            'An apology that never comes',
        ],
        reflection: 'What were you really waiting for, beyond the literal response? What might it look like to give that to yourself, find it elsewhere, or release it?',
    },
    {
        id: 4,
        name: 'Loopback',
        brief: 'You are in conversation with yourself.',
        tech: 'Loopback is when a system communicates with itself. The signal goes out and returns to the same place. It is often used for testing, or for two programs on the same machine to talk to each other.',
        situation: 'You are circling through something on your own.',
        examples: [
            'Rehearsing a conversation in your head',
            'Drafting an unsent message',
            'Ruminating on something that happened',
            'Imagining what someone would say',
            'Turning a decision over repeatedly',
            'Processing a feeling internally',
        ],
        reflection: 'Is this loop helping you work something out, repeating itself, or replacing a step that needs to happen outside it?',
    },
    {
        id: 5,
        name: 'Bridge',
        brief: 'A bridge between two worlds.',
        tech: 'A network bridge connects two network segments so traffic flows between them. More broadly, a bridge links two systems built on different terms.',
        situation: 'You are the connection between two or more separate worlds.',
        examples: [
            'Translating between two people who think very differently',
            'Helping a partner understand your family',
            'Walking an older relative through something unfamiliar',
            'Explaining specialized work to people outside the field',
            "Easing conflict between two people you're both close to",
            'Speaking on behalf of someone whose voice gets overlooked',
            'Connecting friends from one part of your life with friends from another',
        ],
        reflection: 'What does standing between two worlds show you about each? What does seeing them this way change for you?',
    },
    {
        id: 6,
        name: 'Buffer Full',
        brief: "You're already at your limit, and more keeps adding pressure.",
        tech: "A buffer is temporary storage that holds data while it's moving from one place to another. When the buffer fills up, no new input can be accepted until something has been processed out.",
        situation: 'Everything pressing on you at once.',
        examples: [
            'Drowning in unread messages',
            'Falling behind on a growing to-do list',
            'Juggling too many commitments at once',
            'Treating everything coming in as urgent',
            'Working on too many projects at the same time',
            'Being pulled in too many directions',
            'Running from one thing to the next without a break',
        ],
        reflection: 'What in all this actually matters most to you, and what just feels urgent? Seeing the difference can be a real relief.',
    },
    {
        id: 7,
        name: 'Stale Cache',
        brief: "You're working from outdated information.",
        tech: 'A cache stores a copy of data so it can be retrieved quickly without going back to the original source. The cache becomes stale when the original changes but the copy stays the same.',
        situation: 'Going by what used to be true.',
        examples: [
            'Treating someone as the person they used to be',
            'Returning to a place expecting what you remember',
            'Carrying a self-image from years ago',
            "Approaching a relationship like it's still what it was",
            'Going by social rules that have since changed',
            'Acting on what you used to want',
            'Holding to opinions you formed long ago',
        ],
        reflection: "How much of what you see here is what's actually there, and how much is what you've been expecting to see?",
    },
    {
        id: 8,
        name: 'Memory Leak',
        brief: 'Something keeps quietly draining your attention.',
        tech: 'A memory leak is when a program holds onto memory past when it needs it. The held memory builds up over time, and the program slows down as more capacity gets taken.',
        situation: 'Something keeps pulling at you, again and again.',
        examples: [
            'A worry that keeps coming back',
            'A regret that surfaces at quiet moments',
            'A grief still moving through you',
            'An old hurt that returns without warning',
            'A nagging health concern in the background',
            'A simmering tension you carry around',
            'A small disappointment that lingers',
        ],
        reflection: 'Why does this keep coming back to you? What might be there for you to notice?',
    },
    {
        id: 9,
        name: 'Race Condition',
        brief: 'Two priorities are competing for the same moment of yours.',
        situation: 'Two things have arrived at the same time, each with a legitimate claim on you. This is a structural problem, not a personal failing. The conflict comes from the timing, not from anything wrong with either demand.',
        reflection: 'Pick one to go first, even arbitrarily. The cost of choosing is usually lower than the cost of holding both in suspension.',
    },
    {
        id: 10,
        name: 'Cache Miss',
        brief: 'Where you looked turned up empty. What you want is somewhere else.',
        situation: 'The search went to the usual place and found nothing. This can be disorienting, especially when you were confident about where to look. The resource, the connection, the answer, the feeling: it may exist but live somewhere you have not checked yet.',
        reflection: 'Widen the search before concluding the thing is gone. Ask where else it might be.',
    },
    {
        id: 11,
        name: 'Echo',
        brief: 'What you put out is returning to you in the same form.',
        situation: 'The signal you are sending is coming back unchanged. This can mean the environment is confirming you. It can also mean nothing new is entering. If the same things keep reflecting back, the loop may have become closed.',
        reflection: 'Ask what would happen if you changed the signal. What response might that produce?',
    },
    {
        id: 12,
        name: 'Static',
        brief: 'Noise is drowning the signal. The field is full of competing things.',
        situation: 'The thing you are trying to hear or say is present, but the surrounding noise is thick. This applies to a crowded inbox, a loud relationship, a cluttered mind, or any environment where too many things are transmitting at once.',
        reflection: 'Find a way to reduce the ambient noise, even temporarily. The signal will be easier to find once some of the competing sources are quiet.',
    },
    {
        id: 13,
        name: 'Ping',
        brief: 'A small reach-out, low-commitment, checking for presence.',
        situation: 'This is a lightweight move. A small gesture toward someone or something to see if there is anything alive there. It is an offer, not a demand. The purpose is to find out whether the connection is still open before deciding whether to say more.',
        reflection: 'Send the small signal and wait. The response, or its absence, carries real information.',
    },
    {
        id: 14,
        name: 'Throttled',
        brief: 'Your output is being limited. What you would say or do gets squeezed thin on its way through.',
        situation: 'Something is constraining how much of you can come through. The source of the constraint may be external, a role, a relationship, a context that limits what is appropriate. It may also be internal, a habitual holding back that has become automatic. The gap between what is available and what is coming through is worth examining.',
        reflection: 'Locate where the constraint lives. Knowing whether it is outside or inside you changes what options are available.',
    },
    {
        id: 15,
        name: 'Idle',
        brief: 'Capacity is available with nothing using it. The rest is genuine.',
        situation: 'There is a real difference between rest that is earned and capacity held open, and rest that is just avoidance. Right now the situation is one of genuine availability. The work, the demand, the call has lifted or paused. What is here now is space.',
        reflection: 'Let the idle state be what it is. Filling it immediately is one option. Sitting with it is another.',
    },
    {
        id: 16,
        name: 'Polling',
        brief: 'Actively waiting, checking again and again for something to happen.',
        situation: 'You are not passive, but you are also not able to move forward yet. The repeated checking is a way of maintaining alertness while something outside your control resolves. The cost is that each check takes something, and the waiting can come to feel like the whole situation.',
        reflection: 'Ask whether anything about your checking changes the outcome. If not, see whether you can extend the interval between checks.',
    },
    {
        id: 17,
        name: 'Sync',
        brief: 'Things are aligning in time. The rhythms are matching up.',
        situation: 'Whatever you have been working on or waiting for is finding its moment. People, plans, internal states, or external conditions are landing together.',
        reflection: 'Notice what is converging. This kind of alignment does not last forever, so move with it while it holds.',
    },
    {
        id: 18,
        name: 'Latency',
        brief: 'The delay is the situation. Things are happening with a long lag between them.',
        situation: 'Action and response are separated by time. You said something and have not heard back. You started something and the effects have not arrived. The delay is real, and filling the gap with interpretation tends to be costly. What is in transit may still be in transit.',
        reflection: 'Hold the interpretation loosely until something actually arrives. The gap between send and receive is not yet a result.',
    },
    {
        id: 19,
        name: 'Fork',
        brief: 'Paths are diverging and a choice is forming.',
        situation: 'Something that was unified is separating into distinct options, directions, or versions. The divergence may feel like a problem, but it is often just the natural shape of a situation maturing. Both paths are real, and what you choose shapes what comes next.',
        reflection: 'Look at what each path requires of you rather than what each one promises. The requirements are usually more honest than the projections.',
    },
    {
        id: 20,
        name: 'Deadlock',
        brief: 'Two parties each waiting for the other to move first.',
        situation: 'Neither side is refusing to move out of indifference. Each is waiting for a signal from the other before it can proceed. The structure of the situation keeps both suspended. This can happen between people, between parts of yourself, or between competing commitments that each require the other to yield first.',
        reflection: 'Ask whether one party moving unilaterally would actually break the lock. Sometimes it does.',
    },
    {
        id: 21,
        name: 'Merge',
        brief: 'Things that were separate are coming back together.',
        situation: 'Two streams that diverged are rejoining. What was kept apart, whether by circumstance, choice, or time, is being brought into the same space. The joining may be smooth. It may also surface conflicts that developed during the separation, differences that did not exist before the split.',
        reflection: 'Check what has changed in each stream since they parted. The differences are real and worth accounting for before assuming the merge will be seamless.',
    },
    {
        id: 22,
        name: 'Garbage Collection',
        brief: 'Clearing out what has served its purpose. Making room.',
        situation: 'Things that were useful for a time are done now. Holding them keeps the space they occupy from being available for what comes next. This applies to objects, ideas, relationships, projects, and habits alike.',
        reflection: 'Look at what has stayed past its usefulness. Letting it go is the work of this moment.',
    },
    {
        id: 23,
        name: 'Patch',
        brief: 'A quick fix to keep things working. Just enough to bridge the gap.',
        situation: 'This is triage, not repair. Something needed to keep running, and the solution applied was the one that was available. The patch may hold. It may also defer a reckoning with whatever underlying condition made the patch necessary.',
        reflection: 'Use the stability the patch buys to look at what it is covering. The bigger repair may be avoidable now or may not, but knowing what is underneath changes the picture.',
    },
    {
        id: 24,
        name: 'Reset',
        brief: 'Starting over from scratch. The state before is gone.',
        situation: 'Whatever accumulated before has been cleared. This may have happened by choice or by circumstance. The previous configuration, with all its particular entanglements and settled patterns, is no longer running. What comes next builds from a fresh state rather than continuing from where things were.',
        reflection: 'Before filling the cleared space, take a moment with it. What was in the previous configuration that you want to carry forward, and what is better left out of the next one.',
    },
]
