// The 24 cards of The Console.
// Each card describes a recognizable life situation named with a tech metaphor.
// Cards are ordered by type (connection, state, time, change), with each
// type's six cards arranged along an internal spectrum.
export const cards = [
    {
        id: 1,
        name: 'Handshake',
        type: 'connection',
        brief: 'Something new is beginning.',
        tech: 'A handshake is the exchange that two systems use to establish a working connection. Once it completes, the actual work can begin.',
        situation: 'A connection has been established.',
        examples: [
            'Starting a new job',
            'Making a relationship official',
            'Signing a contract',
            'Joining a team or partnership',
            'Initiating a creative collaboration',
        ],
        reflection: 'A handshake establishes a working connection. Two systems exchange information, confirm that they can work together, and then begin communicating. In computing, the uncertainty ends there. In life, starting something new can still feel uncertain even when the decision to do so feels right. With time, things will often begin to feel more natural.',
    },
    {
        id: 2,
        name: 'Bridge',
        type: 'connection',
        brief: 'A connection between separate worlds.',
        tech: 'A network bridge connects two network segments so traffic flows between them. More broadly, a bridge links two systems built on different terms.',
        situation: 'Translation between different perspectives.',
        examples: [
            'Trying to help two people understand each other',
            'Helping a partner understand your family or vice versa',
            'Explaining a job to people outside the field',
            "Mediating a conflict",
            'Moving between different cultural or social environments',
        ],
        reflection: 'A bridge allows communication between separate systems. Because each side operates differently, information often has to be translated as it moves across. In life, people sometimes play a similar role between different groups or perspectives. Spending time in more than one world can broaden the sense of what feels possible or understandable.',
    },
    {
        id: 3,
        name: 'Loopback',
        type: 'connection',
        brief: 'Working something through internally.',
        tech: 'Loopback is when a system communicates with itself, often useful for testing.',
        situation: 'An internal conversation.',
        examples: [
            'Rehearsing a conversation in your head',
            'Revising an unsent message',
            'Ruminating on something that happened',
            'Imagining what someone would say',
            'Wavering on a decision',
        ],
        reflection: 'A loopback routes a signal back into the same system that produced it. No outside input enters the exchange. In computing, loopbacks are useful for testing, calibration, and internal communication. In life, people often do something similar when rehearsing difficult conversations, struggling to make decisions, or trying to predict outcomes. Internal reflection can clarify things up to a point, but some questions only become clearer through input from the outside world.',
    },
    {
        id: 4,
        name: 'Echo',
        type: 'connection',
        brief: 'The same patterns keep repeating.',
        tech: 'An echo is the return of a signal in the same form it was sent.',
        situation: 'Familiar dynamics repeating over time.',
        examples: [
            'Repeating the same conflict in different relationships',
            "Falling into the same role in every social group",
            'Recreating dynamics learned earlier in life',
            'Returning to familiar habits under stress',
            'Having the same argument over and over',
        ],
        reflection: 'An echo is a signal that returns in the same form it was sent. In computing, echoes can confirm that a connection exists, but they do not provide new information. In life, repeated patterns can start to feel inevitable simply because they are so familiar. The same expectations and reactions repeat until they begin reinforcing themselves. Sometimes change only becomes possible when outside input interrupts the pattern.',
    },
    {
        id: 5,
        name: 'Static',
        type: 'connection',
        brief: "Too much noise obscures what matters.",
        tech: 'Static is random noise that gets mixed into a transmission and makes the actual signal hard to hear.',
        situation: 'Difficulty distinguishing what is important.',
        examples: [
            'Struggling to focus amid constant interruptions',
            'Sorting through conflicting advice',
            'Confusing urgency with importance',
            'Trying to choose what you want from too many options',
            'Trying to think clearly while overwhelmed',
        ],
        reflection: "Static is noise that interferes with a signal without replacing it entirely. The message is still there, but it becomes harder to separate from everything competing with it. Human situations can feel similar. In life, clarity can become harder to maintain when too many things are demanding attention at once. Sometimes the signal is still present, even when it becomes difficult to hear clearly.",
    },
    {
        id: 6,
        name: 'Connection Refused',
        type: 'connection',
        brief: 'A clear and direct refusal.',
        tech: 'Connection Refused is a specific TCP error. The rejection is clear, immediate, and definitive.',
        situation: 'A direct, unambiguous no.',
        examples: [
            'A job application denied',
            'An invitation declined',
            'A breakup',
            'Being cut off from further contact',
            'A rejection from a romantic interest',
        ],
        reflection: "Connection Refused is the case where a reachable system actively declines a request. Unlike silence or disconnection, the answer is clear. Human situations sometimes work the same way. A direct refusal can be disappointing, but it also removes uncertainty. Even painful clarity can be easier to live with than endless waiting.",
    },
    {
        id: 7,
        name: 'Firewall',
        type: 'connection',
        brief: 'Not everything is allowed through.',
        tech: 'A firewall filters incoming and outgoing network traffic according to a set of rules. It allows some connections through while blocking others.',
        situation: 'Carefully managing access or exposure.',
        examples: [
            'Being cautious about sharing personal information',
            'Limiting contact with someone who has been harmful',
            'Separating work life from private life',
            'Ignoring inflammatory comments online',
            'Choosing carefully who gets close to you',
        ],
        reflection: 'A firewall filters traffic between systems according to a set of rules. Some requests are allowed through, while others are blocked or restricted. Human situations can work the same way when people limit access to their time, attention, emotions, or personal lives. The goal is often protection, though every filter also determines what can pass through.',
    },
    {
        id: 8,
        name: 'Idle',
        type: 'state',
        brief: 'A period of unoccupied time.',
        tech: 'Idle is when a system has capacity available with nothing currently using it.',
        situation: 'Free time with no demands.',
        examples: [
            'A vacation',
            'An evening with no obligations',
            'A pause between projects',
            'An open Saturday afternoon',
            'Rest after hard work',
        ],
        reflection: 'Idle is when a system has available capacity but no immediate task to perform. The system is functional but at rest. Human life can feel similar during periods of inactivity. In cultures that equate usefulness with constant productivity, stillness can be mistaken for lack of purpose or value.',
    },
    {
        id: 9,
        name: 'Throttled',
        type: 'state',
        brief: "Output is being intentionally limited.",
        tech: 'Throttling is when a system intentionally limits the rate of output.',
        situation: 'Holding back for practical or protective reasons.',
        examples: [
            'Hiding aspects of yourself while at work',
            'Working at a slower speed to avoid overwhelming someone',
            "Not sharing your creative ideas",
            'Speaking carefully to avoid conflict',
            'Editing yourself to avoid offending others',
        ],
        reflection: 'Throttling is when a system intentionally limits its own output. The system\'s full capacity is still present, but its output is being carefully regulated for practical reasons: preventing overload, conserving resources, or adapting to external limits. Human behavior often works the same way. People learn to hold back parts of themselves in certain environments or roles. Sometimes those self-imposed limitations remain in place long after they stop being necessary.',
    },
    {
        id: 10,
        name: 'Buffer Full',
        type: 'state',
        brief: "The system is overloaded.",
        tech: "A buffer temporarily stores incoming data so a system can process it at a manageable rate. If more data arrives than the system can handle, the buffer eventually fills up.",
        situation: 'Too many simultaneous demands.',
        examples: [
            'Drowning in unread messages',
            'Falling behind on a growing todo list',
            'Juggling too many commitments at once',
            'Feeling unable to catch up',
            'Jumping from one thing to the next without a break',
        ],
        reflection: 'A buffer temporarily holds incoming information until it can be processed. When too much information arrives too quickly, the buffer fills and the system begins struggling to keep up. Human life can feel similar during periods of sustained pressure or overload. Attention, energy, and emotional capacity all have limits.',
    },
    {
        id: 11,
        name: 'Stale Cache',
        type: 'state',
        brief: "Working from outdated information.",
        tech: 'A cache stores a copy of data so it can be retrieved quickly without going back to the original source.',
        situation: 'Going by what used to be true.',
        examples: [
            'Treating someone as the person they used to be',
            'Returning to a place expecting it to be unchanged',
            'Keeping an outdated self-image',
            "Not seeing that a relationship has changed",
            'Following social rules that have since evolved',
            'Holding on to opinions you formed long ago',
        ],
        reflection: 'A cache stores previously retrieved information so it can be reused quickly. Problems appear when the stored version no longer matches the current reality. Human life can feel similar when old beliefs or expectations continue to affect how the present is perceived. Revising these outdated assumptions usually requires observing things as they currently are, as change is not always noticeable from the inside.',
    },
    {
        id: 12,
        name: 'Memory Leak',
        type: 'state',
        brief: 'Something unresolved is draining energy.',
        tech: 'A memory leak is when a program holds onto memory past when it needs it.',
        situation: 'Something keeps bothering you.',
        examples: [
            'A recurring worry',
            'A frequent regret',
            'An unprocessed loss',
            'Repeatedly reliving a painful experience',
            'A nagging health issue',
        ],
        reflection: 'A memory leak happens when a system continues holding onto resources it no longer needs. The system keeps functioning, but over time this drain begins to affect performance. Human life can feel similar when unresolved worries, grief, or stress occupy more and more mental and emotional space. The result is often a growing sense of fatigue or heaviness that may be difficult to trace to any single cause.',
    },
    {
        id: 13,
        name: 'Crash',
        type: 'state',
        brief: 'A sudden and disruptive ending.',
        tech: 'A crash is when a system stops running suddenly because of an error that broke it.',
        situation: 'Something important has abruptly stopped.',
        examples: [
            'A relationship that ended',
            'A sudden loss in the family',
            'An unexpected health crisis',
            'A job or career ending abruptly',
            'A mental or emotional breakdown',
        ],
        reflection: 'A crash is when a system stops suddenly before its current state can be fully preserved. Information that was never saved may be lost when the process ends abruptly. Human life can feel similar when something suddenly changes in a way that cannot be undone. Recovery is rarely as simple as restarting from where things left off. Life after a crash often means adapting to both what remains and what was lost.',
    },
    {
        id: 14,
        name: 'Queue',
        type: 'state',
        brief: 'Things are waiting their turn.',
        tech: 'A queue is an ordered line of tasks or requests waiting to be processed one at a time.',
        situation: 'A backlog waiting for attention.',
        examples: [
            'Unread messages piling up',
            'Putting off difficult conversations',
            'A todo list of household tasks',
            'Unresolved decisions waiting for attention',
            'Creative ideas that never lead to action',
        ],
        reflection: 'A queue is a list of work waiting to be processed in order. Human life can feel similar when too many responsibilities or demands compete for limited time and attention. Some things remain unfinished not because they do not matter, but because there is only so much that can be handled at once.',
    },
    {
        id: 15,
        name: 'Heartbeat',
        type: 'time',
        brief: 'A steady rhythm that keeps something alive.',
        tech: 'A heartbeat is a regular signal sent at fixed intervals so other systems know a process is still alive.',
        situation: 'A repeated action that sustains connection.',
        examples: [
            'Calling your parents every week',
            'Going to therapy even when you feel fine',
            'Following a daily routine',
            'Walking the dog every morning',
            'Tending to the basics of food, sleep, and movement',
        ],
        reflection: 'A heartbeat is a repeated signal that indicates a system is still functioning. The signal may seem small on its own, but over time its regularity becomes meaningful. Human life often works the same way. Relationships and routines are usually maintained through small, consistent actions.',
    },
    {
        id: 16,
        name: 'Sync',
        type: 'time',
        brief: 'Alignment that enables cooperation.',
        tech: 'Sync is when two or more systems align in time so their actions happen together, or they reach the same state at once.',
        situation: 'Independent things aligning into coordinated action.',
        examples: [
            'A team working together effectively',
            'A creative breakthrough from collaboration',
            'Two people immediately understanding each other',
            'An event coming together',
            'Being on the same wavelength with someone else',
        ],
        reflection: 'Synchronization is the alignment of separate systems so they can work together effectively. Human situations sometimes work the same way. Good collaboration often depends on people and circumstances aligning in ways that cannot always be anticipated.',
    },
    {
        id: 17,
        name: 'Polling',
        type: 'time',
        brief: "Repeatedly looking for an update.",
        tech: 'Polling is when a system repeatedly checks for a status update at regular intervals.',
        situation: 'Waiting and checking again.',
        examples: [
            'Reloading your inbox waiting for a reply',
            'Checking your phone repeatedly for a text',
            'Watching for news of a pending event',
            'Checking the mail for an expected package',
            'Watching the door for someone to arrive',
        ],
        reflection: 'Polling is the repeated checking for updates at regular intervals, returning the same result unless something has changed. Human situations often work the same way during times of uncertainty or anticipation. Repeated checking may not change the outcome, but it can make waiting feel less passive.',
    },
    {
        id: 18,
        name: 'Latency',
        type: 'time',
        brief: "A long wait between action and result.",
        tech: 'Latency is the delay between when something is sent and when it arrives.',
        situation: 'Time passing between cause and effect.',
        examples: [
            "A message you sent that hasn't been answered yet",
            'A decision whose consequences are still undetermined',
            "A career move that hasn't paid off so far",
            "A new habit that hasn't changed your life yet",
            'A medical treatment that takes weeks to start working',
        ],
        reflection: 'Latency is the delay between an action and its observable result. Human life can feel similar at times when consequences or changes remain unknown. Uncertainty often encourages people to imagine possible outcomes, but an unresolved situation is not yet a final result.',
    },
    {
        id: 19,
        name: 'Timeout',
        type: 'time',
        brief: 'Waiting for a response that never arrives.',
        tech: 'A timeout is when a system gives up waiting for a response. After a configured time, the request is treated as failed.',
        situation: 'Silence where an answer was expected.',
        examples: [
            'A job application that goes unanswered',
            'A date request that gets ignored',
            'A friendship that fades away',
            'A promise that never gets fulfilled',
            'An apology that never comes',
        ],
        reflection: 'A timeout occurs when a system stops waiting after no response arrives within a certain amount of time. The lack of a reply does not always indicate whether the message was ignored, missed, or never received. Human life can feel similar when silence leaves situations unresolved without an explanation. Sometimes the only decision available is whether to continue waiting.',
    },
    {
        id: 20,
        name: 'Deadlock',
        type: 'time',
        brief: 'Both sides are stuck, each waiting for the other to make the first move.',
        tech: 'A deadlock is when two or more processes are each waiting for the other to release something.',
        situation: 'Two sides waiting for the other to take action.',
        examples: [
            'After an argument, friends waiting for each other to apologize',
            'Two cars at an intersection, each waiting for the other to move first',
            'A negotiation frozen with both sides waiting for the other to budge',
            'Two people interested in each other, both waiting for the other to reach out',
            'A meeting where no one wants to be the first to speak',
        ],
        reflection: 'A deadlock occurs when multiple systems are each waiting for the others before they can continue. As long as every side continues waiting, nothing changes. Human situations can work the same way when pride or caution prevent anyone from acting first. Deadlocks often persist until someone becomes willing to act without knowing how the other side will respond.',
    },
    {
        id: 21,
        name: 'Retry',
        type: 'time',
        brief: 'Trying again after failure or interruption.',
        tech: 'A retry is when a system attempts an operation again after it fails or receives no response.',
        situation: 'Trying again under uncertain conditions.',
        examples: [
            'Reapplying after being rejected',
            'Trying to reconnect after losing touch',
            'Returning to a skill after struggling with it',
            'Attempting a difficult conversation again',
            'Starting over on a project that previously failed',
        ],
        reflection: 'A retry is another attempt made after an operation does not succeed. Some failures only happen because conditions were wrong at the time. Human life can feel similar when people choose to try again after disappointment, rejection, or interruption. The outcome may still remain uncertain, but uncertainty is not the same thing as impossibility.',
    },
    {
        id: 22,
        name: 'Patch',
        type: 'change',
        brief: 'A quick fix to keep things going for now.',
        tech: 'A patch is a small, quick change made to fix a specific problem.',
        situation: 'A temporary fix.',
        examples: [
            'Patching a flat tire',
            'Taking medicine for symptoms until you can determine the cause',
            'Negotiating a temporary work arrangement',
            'Finding a temporary compromise during conflict',
            'Borrowing money to cover an unexpected expense',
        ],
        reflection: 'A patch is a small change that addresses an immediate problem without fully rebuilding the underlying system. The issue may not be completely resolved, but the system can continue functioning. Human life often works the same way. Temporary solutions may not fix everything, but they can provide time and stability to work on the larger problems.',
    },
    {
        id: 23,
        name: 'Branch',
        type: 'change',
        brief: 'A choice between different paths.',
        tech: 'A branch is a divergent line of development that splits off from the main one.',
        situation: 'Weighing options before deciding.',
        examples: [
            'Keeping your current job or accepting a new offer',
            'Committing to a relationship or remaining single',
            'Speaking up about something or keeping it to yourself',
            'Staying close to family or moving far away',
            'Doing what you really want or what is expected of you',
        ],
        reflection: 'A branch occurs when one path splits into multiple possible directions. Human situations can feel similar at moments where important choices create different potential futures. No option comes with complete certainty, and it often takes time to fully understand the consequences of a decision.',
    },
    {
        id: 24,
        name: 'Merge',
        type: 'change',
        brief: 'Two separate things are coming together.',
        tech: 'A merge is when two separate branches of work are combined into one.',
        situation: 'Independent paths becoming connected.',
        examples: [
            'Reconnecting with a partner after time apart',
            'Combining two separate work projects into one',
            'Merging previously separate identities',
            'Moving in together',
            'Two families becoming one',
        ],
        reflection: 'A merge occurs when separate systems are combined into one. Human life can feel similar when relationships, identities, or responsibilities begin connecting more closely. The result often contains elements of both sides, but is also something entirely new.',
    },
    {
        id: 25,
        name: 'Garbage Collection',
        type: 'change',
        brief: 'Releasing what has served its purpose.',
        tech: 'Garbage collection is the automatic process by which a system reclaims memory that is no longer useful. The reclaimed space becomes available for new work.',
        situation: 'Making room for what comes next.',
        examples: [
            'Letting go of an old grudge',
            "Giving away clothes you haven't worn in years",
            "Quitting a habit you've outgrown",
            "Growing apart from someone over time",
            "Donating books you've already read",
        ],
        reflection: 'Garbage collection frees memory that is no longer being actively used by the system. Without occasional clearing, resources remain tied up unnecessarily over time. Human life can feel similar when old items, habits, or emotional attachments continue occupying space after they no longer serve a purpose. Unlike computers, people usually have to consciously choose what they are ready to release.',
    },
    {
        id: 26,
        name: 'Upgrade',
        type: 'change',
        brief: "Replacing old limitations with new capabilities.",
        tech: 'An upgrade replaces a system with a newer version that has more capabilities or improvements.',
        situation: 'Expanding what is possible.',
        examples: [
            'Getting better at something through practice',
            'Moving into a home that better fits your needs',
            'Replacing outdated tools with better ones',
            'Stepping into a more challenging role',
            'Personal growth from therapy',
        ],
        reflection: 'An upgrade changes a system so it can operate more effectively or perform new tasks. Human life can feel similar when better tools or more experience change what a person is able to accomplish. Sometimes this progress is easiest to recognize in situations that no longer feel as difficult as they once did.',
    },
    {
        id: 27,
        name: 'Reset',
        type: 'change',
        brief: 'Starting over after major change.',
        tech: 'A reset returns a system to its starting state.',
        situation: 'Beginning again.',
        examples: [
            'Starting over after a major life change',
            'Picking up the pieces after a relationship ends',
            'Going back to school as an adult',
            'Changing jobs or careers',
            'Moving to a new home',
        ],
        reflection: 'A reset returns a system to a stable starting condition after normal operation has been interrupted. Human life can feel similar after major changes that require rebuilding in a new direction. Unlike computing systems, people do not return to exactly who they were before the reset.',
    },
    {
        id: 28,
        name: 'Backup',
        type: 'change',
        brief: 'Protecting against irreversible loss.',
        tech: 'A backup is a preserved copy of data that can be restored if the original is lost, damaged, or corrupted.',
        situation: 'Preserving something important before change or risk.',
        examples: [
            'Saving messages or photos from an important relationship',
            'Keeping emergency savings',
            'Recording family stories or recipes',
            'Holding onto skills from a previous career',
            'Creating copies of important documents',
        ],
        reflection: 'A backup preserves something important so it can survive unexpected loss or disruption. Human situations can feel similar when people hold onto memories, relationships, or resources that they may need later. Preparing for loss can be a way of protecting what matters most.',
    },
]
