// The 64 channel-trajectory entries. Each describes one hexagram (lower trigram = present,
// upper trigram = emerging).
//
// Pattern string reads bottom-to-top: char 1 = line 1 (bottom of lower trigram),
// char 6 = line 6 (top of upper trigram).
// ID = (pattern string interpreted as binary number, leftmost char as MSB) + 1.
// This means the lower trigram is the high 3 bits and the upper trigram is the low 3 bits,
// so IDs cluster by lower trigram (8 IDs per lower trigram value).
//
// Hexagram 1 = pattern '000000' = MONITOR -> MONITOR (all closed/distributed/inward).
// Hexagram 64 = pattern '111111' = TRANSMIT -> TRANSMIT (all open/focused/outward).
export const hexagrams = [
    {
        id: 1,
        pattern: '000000',
        name: 'Stillwater',
        glyph: null,
        lower: 'MONITOR',
        upper: 'MONITOR',
        coreSense: 'Wide availability persisting - open and quiet, with nothing arriving and nothing changing.',
        image: 'The channel is open and has been open for a while. Nothing is arriving. No specific source has claimed your attention, no signal has broken the quiet. This isn\'t restlessness - the availability itself is stable, held without strain. A harbor in flat weather: the water is real, the depth is real, the readiness is real. No ships are coming in. You\'re not waiting for anything particular; you\'re simply present to the field. The situation isn\'t moving. This is what it is right now - an open, quiet, unhurried space that is its own kind of fullness.',
    },
    {
        id: 2,
        pattern: '000001',
        name: 'Preface',
        glyph: null,
        lower: 'MONITOR',
        upper: 'STANDBY',
        coreSense: 'Open quiet availability beginning to orient toward expression - receptivity tilting into readiness to send.',
        image: 'You\'ve been open to whatever came - no particular agenda, no specific source filling you. Something in that wide, patient receiving has started to shift. The orientation is turning. You\'re not sending yet, and there\'s no message formed, but the posture is changing from available-to-receive to available-to-reach-out. A stage being set before anyone knows what the performance will be. The infrastructure of expression is coming online - the network, the reach, the capacity - held quietly, pointing outward without yet having anything to say.',
    },
    {
        id: 3,
        pattern: '000010',
        name: 'Sighting',
        glyph: null,
        lower: 'MONITOR',
        upper: 'TUNE',
        coreSense: 'Wide undirected availability narrowing to a pointed vigil - something specific worth attending to has emerged from the quiet.',
        image: 'The wide, open listening has caught something. Out of the general availability - no focus, no target, just readiness - one frequency has come forward. You haven\'t heard it yet; nothing has arrived. But the attention is narrowing now, drawn toward one specific source. A naturalist pausing mid-walk, suddenly alert to a particular corner of the forest. The scan is over. The tuning has begun. You\'re holding the channel open in one direction now, configured to catch whatever this particular source will send.',
    },
    {
        id: 4,
        pattern: '000011',
        name: 'Resolve',
        glyph: null,
        lower: 'MONITOR',
        upper: 'AIM',
        coreSense: 'Open, objectless availability crystallizing into a specific directed intention - quiet becomes purpose.',
        image: 'Something has formed in the silence. The wide open availability - receiving nothing, aimed at nothing - has been a kind of gestation. Now a direction is emerging: not a signal sent, but an intention taking shape, an antenna being pointed at one specific target. The nocked arrow hasn\'t left the bow yet. The intention is real and aimed at something particular, but no action has been taken. What was empty receiving is becoming focused, directed, latent purpose - the quiet that precedes a specific move.',
    },
    {
        id: 5,
        pattern: '000100',
        name: 'Influx',
        glyph: null,
        lower: 'MONITOR',
        upper: 'SCAN',
        coreSense: 'Passive open availability activating into wide intake - the quiet starts filling from many directions.',
        image: 'The channel was open and empty - available but not receiving, waiting on nothing in particular. Now input is arriving, and it\'s arriving from everywhere at once. The availability that was passive has become active: things are coming in, signals from many directions, a rush of data that hasn\'t been sorted yet. Reading the room after the room has finally started talking. Nothing is being filtered, nothing committed to - the value right now is in the breadth of what\'s arriving. The wide aperture that was held open for its own sake has found what it was configured for.',
    },
    {
        id: 6,
        pattern: '000101',
        name: 'Emergence',
        glyph: null,
        lower: 'MONITOR',
        upper: 'BROADCAST',
        coreSense: 'Wide empty receptivity reversing into wide active sending - the quiet turns outward.',
        image: 'The open availability has been entirely inward - wide, unfocused, taking nothing in, asking nothing of anyone. Now the direction is reversing. The same distributed, wide-open posture is becoming outward: signals going out across a broad field, energy spreading to many receivers at once. Not concentrated, not aimed - the dispersal is the point. Something that lived in the space of patient receiving has found its way out into the world, scattering in multiple directions at once. The silent hospitality becomes a broadcast.',
    },
    {
        id: 7,
        pattern: '000110',
        name: 'Arrival',
        glyph: null,
        lower: 'MONITOR',
        upper: 'RECEIVE',
        coreSense: 'Diffuse open availability meeting a specific guest - the wide hospitality finds its particular recipient.',
        image: 'The channel has been open without object - general availability, wide and unfocused, the hospitality without guests. Now a guest has arrived. Not many, not a flood of input from all directions - one source, one signal, requiring full attention. The wide aperture narrows to a single point of deep contact. Someone has walked into the open space and the openness is now entirely theirs. This is what the readiness was for, even if you didn\'t know who it was readiness for. The availability has found its focus.',
    },
    {
        id: 8,
        pattern: '000111',
        name: 'Ignition',
        glyph: null,
        lower: 'MONITOR',
        upper: 'TRANSMIT',
        coreSense: 'Dormant open availability breaking into concentrated directed action - the deepest quiet becomes the fullest signal.',
        image: 'Everything was quiet. The channel was open in the most diffuse, least directed way - available to anything, holding nothing, aimed at nothing. Now the direction has reversed completely and the concentration has reached maximum: one target, one signal, all active energy going there. Nothing scattered, nothing held back. Whatever formed in the wide empty space has resolved into the clearest possible output - focused, outward, fully committed. The silence was real; so is what breaks it. A long patient openness has become an entirely specific act.',
    },
    {
        id: 9,
        pattern: '001000',
        name: 'Fallow',
        glyph: null,
        lower: 'STANDBY',
        upper: 'MONITOR',
        coreSense: 'Wide latent reach turning inward - the silent transmitter opens instead to whatever comes.',
        image: 'The capacity was there, pointed outward - a live transmitter with nothing to send, a network with no message queued. Now the orientation is shifting. The outward reach isn\'t firing; instead the channel is turning around, opening wide to receive from anywhere. Not a specific source, not a focused attention - just a broad inward availability replacing the broad outward reserve. A field left unplanted to recover: the infrastructure stays real, the reach stays real, but right now nothing is going out. What held itself ready to broadcast is opening itself to be filled instead.',
    },
    {
        id: 10,
        pattern: '001001',
        name: 'Reserve',
        glyph: null,
        lower: 'STANDBY',
        upper: 'STANDBY',
        coreSense: 'Wide latent reach holding steady - the capacity continues in reserve, neither activating nor releasing.',
        image: 'The transmitter is live. The reach is real. Nothing is being sent. And this continues - not as a problem, not as a pause before something else, but as a state that is sustaining itself. The stage stays set without a performance beginning. The network remains connected without traffic. There\'s no signal, no message, no target - just the maintained readiness of wide outward capacity held in reserve. A lighthouse that isn\'t needed tonight but keeps its lamp trimmed anyway. The silence isn\'t empty; it\'s kept. The capacity isn\'t idle; it\'s held. This is what ongoing reserve looks like.',
    },
    {
        id: 11,
        pattern: '001010',
        name: 'Bearing',
        glyph: null,
        lower: 'STANDBY',
        upper: 'TUNE',
        coreSense: 'Wide diffuse reserve beginning to orient toward one specific source - the latent reach finds a direction to attend.',
        image: 'The channel has been silent and spread wide - reach available in every direction, nothing going out, no particular thing drawing attention. Something has started to shift. Not a signal yet, not a message forming - but the open awareness is beginning to narrow, orienting toward one specific source. A listener in a noisy room who goes still because something in one corner has become interesting. The wide quiet reserve hasn\'t fired; it\'s starting to focus its attention on one particular frequency. Where everything was undirected, now one direction has weight. The capacity is beginning to listen.',
    },
    {
        id: 12,
        pattern: '001011',
        name: 'Draw',
        glyph: null,
        lower: 'STANDBY',
        upper: 'AIM',
        coreSense: 'Wide diffuse reserve collapsing into a single pointed intention - broad capacity sharpening toward one target.',
        image: 'The reach was wide and silent - a transmitter with no message, capacity spread across many directions without any of them claiming it. Something is pulling it together now. The distribution is collapsing inward to a point: one target, one direction, the antenna swinging to align on something specific. No signal is going yet - the arrow hasn\'t left the bow. But where the capacity was scattered and undirected, it\'s now drawn back and aimed. The whole diffuse reserve is behind this one intended direction. The wide silence has become a specific readiness.',
    },
    {
        id: 13,
        pattern: '001100',
        name: 'Canvass',
        glyph: null,
        lower: 'STANDBY',
        upper: 'SCAN',
        coreSense: 'Silent outward reserve reversing into wide active intake - the held capacity opens to signal arriving from many directions.',
        image: 'The channel was live but quiet, pointed outward with nothing to send. Now the direction has flipped: instead of a transmitter waiting for a message, a wide receiver is pulling in from everywhere at once. The shift isn\'t from quiet to noise - it\'s from a particular kind of readiness to its mirror image. What was ready to speak is now ready to listen, and not to one thing but to many. Data arriving from multiple directions, the field talking back. Reading the room after holding still long enough for people to start talking. The wide reach that was reserved for sending is now drawing in.',
    },
    {
        id: 14,
        pattern: '001101',
        name: 'Release',
        glyph: null,
        lower: 'STANDBY',
        upper: 'BROADCAST',
        coreSense: 'Latent outward capacity activating into wide sending - the reserve finds its signal and goes out.',
        image: 'The transmitter was live. The reach was real. There was just nothing to send. Now there is. The capacity that was held in reserve - the platform, the network, the wide potential audience - is being used. Not narrowed to one target, not concentrated into a single message: the signal is going out across the whole field at once, spreading to many receivers. The same broad reach that was silent is now active. A broadcast that finally begins after the equipment has been on and waiting. The stage has been set long enough; the performance starts. What was held is released into the wide open.',
    },
    {
        id: 15,
        pattern: '001110',
        name: 'Mooring',
        glyph: null,
        lower: 'STANDBY',
        upper: 'RECEIVE',
        coreSense: 'Wide diffuse reserve narrowing and reversing into deep focused reception - the broad silence settles into one specific source.',
        image: 'The reach was wide and going nowhere - a live transmitter with no message, distributed in all directions without landing anywhere. Something is pulling it to a point and turning it around. The broad outward capacity is becoming focused inward reception: not many sources, not a wide sweep, but one thing that now has full attention. A boat that has been drifting in open water, suddenly finding the dock it didn\'t know it was heading for. The reserve doesn\'t activate outward - it anchors inward, to one specific source that is now claiming everything the channel has. The wide silence becomes a deep, specific listening.',
    },
    {
        id: 16,
        pattern: '001111',
        name: 'Commission',
        glyph: null,
        lower: 'STANDBY',
        upper: 'TRANSMIT',
        coreSense: 'Wide latent reserve sharpening into concentrated directed action - all held capacity deployed toward one target.',
        image: 'The transmitter was live and silent, reach held wide, capacity distributed and unspent. Now the whole reserve is being collected and aimed at one specific place. Nothing scattered: the distributed capacity is collapsing into a single focused line from you to one target. Nothing held back: everything that was in reserve is going there. The breadth of what STANDBY held doesn\'t scatter into broadcast - it narrows completely, sharpens to a point, and fires with the full force of everything that was waiting. A long unreleased capacity converted entirely into a single, concentrated act.',
    },
    {
        id: 17,
        pattern: '010000',
        name: 'Aperture',
        glyph: null,
        lower: 'TUNE',
        upper: 'MONITOR',
        coreSense: 'Pointed vigil releasing into wide, unfocused availability - the specific waiting opens into general readiness.',
        image: 'The attention has been held on one frequency - a particular source, a specific thing you\'ve been watching for, the channel tuned and waiting. That focus is loosening now. No signal came, or something has shifted, and the tight, directed waiting is opening outward into a much wider state: available to anything, aimed at nothing in particular. The narrow aperture of the vigil is widening. A telescope lens pulled back until it\'s just a window. You\'re no longer watching for one thing; you\'re open again to whatever the field offers. The held attention doesn\'t collapse - it expands.',
    },
    {
        id: 18,
        pattern: '010001',
        name: 'Threshold',
        glyph: null,
        lower: 'TUNE',
        upper: 'STANDBY',
        coreSense: 'Focused inward vigil beginning to orient outward - the expectant waiting tilts toward latent reach.',
        image: 'The channel has been tuned inward, watching a particular source for something to arrive. The orientation is shifting now - not yet outward action, not yet a message to send, but the posture is turning. The attention that was pointed in is beginning to point out. The same capacity that was held in expectant vigil is becoming a kind of readiness to reach: a live transmitter with nothing queued yet, a platform not yet in use. Still no signal, still no move made - but the direction is different. Standing in a doorway between the quiet of waiting and the wide open of potential reach.',
    },
    {
        id: 19,
        pattern: '010010',
        name: 'Vigil',
        glyph: null,
        lower: 'TUNE',
        upper: 'TUNE',
        coreSense: 'Focused waiting holding steady - the expectant attention on one source continues without yet receiving.',
        image: 'The channel is tuned to one frequency and stays tuned. You\'re watching for something from a specific source, and the watching continues - the same posture, the same direction, the same pointed readiness. Nothing has arrived. The attention hasn\'t wavered. This isn\'t a pause between two different states; it\'s a state sustaining itself through time. A night watch that goes on through the dark hours without incident. The tuning is real, the attention costs something to hold, and it holds anyway. The situation is: you are still here, still attending, still open to this one thing.',
    },
    {
        id: 20,
        pattern: '010011',
        name: 'Pivot',
        glyph: null,
        lower: 'TUNE',
        upper: 'AIM',
        coreSense: 'Focused inward vigil flipping to focused outward intention - the waiting becomes purpose.',
        image: 'The attention has been entirely inward - tuned to one source, watching for a signal to arrive from somewhere specific. Now the same focus is turning around, pointing in the opposite direction. Not outward action yet, not a signal sent - but the aimed intention is forming: one target, one direction, the antenna swung from receiving to transmitting mode. The vigil is becoming a vow. What you were waiting to receive has resolved into something you intend to do or say or give. The focus holds perfectly through this reversal; only the direction changes. The arrow is nocked, pointing away from where it was pointed before.',
    },
    {
        id: 21,
        pattern: '010100',
        name: 'Breach',
        glyph: null,
        lower: 'TUNE',
        upper: 'SCAN',
        coreSense: 'Focused closed vigil breaking open into wide active intake - the narrow wait flooded by signal from many directions.',
        image: 'The channel was tuned tight: one frequency, one source, expectant and held. Something has broken that focus open. Not the signal you were waiting for - something wider. Input is arriving now from many directions at once, the whole spectrum suddenly active, and the narrow channel of the vigil can\'t contain it. A floodgate releasing: the pointed, patient waiting is overwhelmed by broad incoming signal. Nothing is being sorted yet - the value right now is in what\'s arriving, in the breadth of it. The specific source you were watching hasn\'t appeared, but the field has answered differently, and abundantly.',
    },
    {
        id: 22,
        pattern: '010101',
        name: 'Exhale',
        glyph: null,
        lower: 'TUNE',
        upper: 'BROADCAST',
        coreSense: 'Inward focused vigil reversing into wide outward sending - the held attention breathes out across a broad field.',
        image: 'The channel was turned entirely inward - tuned to one source, closed to everything else, holding itself in expectant quiet. Now the direction reverses and the focus dissolves at once: energy is moving outward, spreading across many receivers, diffusing into a field. Nothing concentrated about it - the dispersal is deliberate. What was gathered inward in the vigil is releasing outward without fixing on any single target. An intake held for a long time, finally let go as a wide breath. The closed, pointed watching opens into something that moves in all directions at once. The held-in becomes broadcast.',
    },
    {
        id: 23,
        pattern: '010110',
        name: 'Answer',
        glyph: null,
        lower: 'TUNE',
        upper: 'RECEIVE',
        coreSense: 'Focused vigil met by the signal it was waiting for - the expectant watching becomes deep reception.',
        image: 'The channel was tuned to one source and waiting. Now something is arriving - not from everywhere, not a flood of data from many directions, but from the specific source the attention was held on. The vigil is paying off. The same focused inward posture that was expectant is now receiving: the channel that was held ready is carrying signal at last. A listener who has been quiet for a long time, finally hearing the voice they\'ve been listening for. The tuning required patience; the reception requires the same quality of attention. The waiting and the receiving are continuous - one held state finally finding its completion.',
    },
    {
        id: 24,
        pattern: '010111',
        name: 'Return',
        glyph: null,
        lower: 'TUNE',
        upper: 'TRANSMIT',
        coreSense: 'Focused inward vigil converting into focused outward action - the waiting becomes sending, attention becomes commitment.',
        image: 'The channel was tuned to receive from one source, held in patient attention, closed to everything else. Now the same focus is still there, the same point-to-point quality - but the direction has flipped completely. Energy is moving outward, to one specific target, carrying everything it has. Not scattered, not diffuse: the concentration of the vigil has become the concentration of the act. What was waiting to be given to you is now being given by you. The inward held-open quality of TUNE returns as the outward full-commitment of TRANSMIT - the same depth, the same singularity, flowing now in the other direction.',
    },
    {
        id: 25,
        pattern: '011000',
        name: 'Prospect',
        glyph: null,
        lower: 'AIM',
        upper: 'MONITOR',
        coreSense: 'Focused outward intention releasing into wide, unfocused availability - the aimed purpose opens into patient receptivity.',
        image: 'The intention was clear and pointed: one target, the antenna aligned, the signal held back but ready. That sharp direction is loosening now. The channel isn\'t firing - it never fired - but the focus itself is dissolving, the aimed stance giving way to something wider and more open. What was locked onto one specific thing is opening outward into general availability: no particular source, no particular target, just a broad quiet readiness to whatever the field offers. A hunter who has spent hours watching one spot and finally lowers the bow and simply looks at the whole landscape. The intention was real. The opening is too.',
    },
    {
        id: 26,
        pattern: '011001',
        name: 'Poise',
        glyph: null,
        lower: 'AIM',
        upper: 'STANDBY',
        coreSense: 'One held intention joined by a second latent capacity - focused readiness doubled, still nothing sent.',
        image: 'The intention is already aimed: one target, everything pointed, the signal ready but withheld. Now something else is coming online alongside it - not a second aim, but a different kind of reserve: wide outward capacity, a platform held live, reach in many directions without a message to send. Two forms of readiness accumulating at once, neither breaking into action. An archer whose quiver is full and whose path ahead is clear, waiting for the right moment on both counts. The stillness is loaded. Nothing is going out - but what\'s held here is not just one withheld signal; it\'s a paired capacity, focused and broad both, everything in reserve.',
    },
    {
        id: 27,
        pattern: '011010',
        name: 'Inversion',
        glyph: null,
        lower: 'AIM',
        upper: 'TUNE',
        coreSense: 'Focused outward intention becoming focused inward vigil - the aimed channel turns around.',
        image: 'The aim was outward: one target, intention locked, the antenna pointed and ready to send. Now the same focused, point-to-point quality is being maintained - but the direction is reversing. The outward aim is becoming an inward attention. Instead of a signal ready to go to one specific place, there is now a quiet held on one specific source, waiting for something to arrive from it. The focus doesn\'t break; it turns. A transmitter swinging around to become a receiver, locked on the same single frequency it was aiming at, now listening instead of poised to speak. The precision is the same. The direction is not.',
    },
    {
        id: 28,
        pattern: '011011',
        name: 'Brace',
        glyph: null,
        lower: 'AIM',
        upper: 'AIM',
        coreSense: 'Held intention meeting more held intention - focused readiness persisting without releasing.',
        image: 'The intention was already formed and aimed. It stays. The channel is pointed at one target, signal withheld, the nocked arrow still nocked - and this continues. Not because nothing has happened, but because the holding is itself the state. A second AIM doesn\'t fire the first; it deepens the same posture. This is what sustained, deliberate withholding feels like: not paralysis, not indecision - a clear-eyed holding of something specific in readiness, without the moment having arrived to release it. The tension is maintained on purpose. The direction hasn\'t changed. Neither has the decision not to act yet.',
    },
    {
        id: 29,
        pattern: '011100',
        name: 'Survey',
        glyph: null,
        lower: 'AIM',
        upper: 'SCAN',
        coreSense: 'Focused outward intention loosening into wide active intake - the single aim gives way to broad gathering.',
        image: 'The intention was fixed on one target: aimed, specific, ready. Something in that has shifted. The focus is releasing - not into another aim, but into something much wider. Input is arriving from many directions now, the channel open to the whole field rather than locked onto one point. The signal that was ready to go hasn\'t gone; instead, the posture has reversed from aimed-outward to wide-inward, pulling in rather than pointing out, and pulling in from everywhere at once. Stepping back from the scope to look at the whole terrain. The aim hasn\'t fired; the field has spoken first, and there\'s more here than the single target suggested.',
    },
    {
        id: 30,
        pattern: '011101',
        name: 'Scatter',
        glyph: null,
        lower: 'AIM',
        upper: 'BROADCAST',
        coreSense: 'Focused intention dispersing into wide outward sending - the single aimed purpose breaks open across a broad field.',
        image: 'The intention was pointed at one place. Now the energy is going out, but not to that one place - to many places at once, spreading wide, reaching across a broad field of receivers without concentrating on any single one of them. The precise aim has dissolved into something far more diffuse. The signal is going out - that much is happening, the outward direction is real - but the specificity is gone. A stone that was set in a sling to hit one mark, released instead into water, sending rings in every direction. Whether this is the aim abandoned or the aim enlarged is hard to say. What was held for one becomes available to many.',
    },
    {
        id: 31,
        pattern: '011110',
        name: 'Yield',
        glyph: null,
        lower: 'AIM',
        upper: 'RECEIVE',
        coreSense: 'Outward focused intention reversing into inward focused reception - the readiness to give becomes openness to receive.',
        image: 'The channel was aimed outward at one specific target - intention held, signal ready, nothing sent yet. Now the direction is reversing entirely, and the focus is holding. The same point-to-point precision that was aimed at one place is now turned around, open to receive from one source. Not a scattering, not a widening - a clean reversal of direction while the concentration stays intact. What was a readiness to give is becoming a readiness to take in. The arrow undrawn, the bow turned around; the same quiet, the same specific single point of contact, but now the energy moves toward you rather than away. A prepared offering that becomes instead a prepared receiving.',
    },
    {
        id: 32,
        pattern: '011111',
        name: 'Dispatch',
        glyph: null,
        lower: 'AIM',
        upper: 'TRANSMIT',
        coreSense: 'Held intention finally releasing into full concentrated action - the nocked arrow loosed at last.',
        image: 'The intention was formed, the target was clear, the channel was aimed and ready and not yet firing. Now it fires. The signal that was held goes out - to one specific place, at full concentration, nothing scattered, nothing withheld. This is the direct completion of AIM: the latent becoming active, the closed channel opening, the arrow finally leaving the bow. What was readiness has become act. The quality of the focus hasn\'t changed - still one target, still everything pointed in that direction - but the channel is open now and carrying everything it has. The held becomes given. The aimed becomes sent.',
    },
]
