// The 64 channel-trajectory entries. Each describes one hexagram (lower trigram = present,
// upper trigram = emerging).
//
// Pattern string reads bottom-to-top: char 1 = line 1 (bottom of lower trigram),
// char 6 = line 6 (top of upper trigram).
// ID = (pattern string interpreted as binary number, leftmost char as MSB) + 1.
// This means the lower trigram is the high 3 bits and the upper trigram is the low 3 bits,
// so IDs cluster by lower trigram (8 IDs per lower trigram value).
//
// Hexagram 1 = pattern '000000' = MONITOR -> MONITOR (all closed/distributed/inward).
// Hexagram 64 = pattern '111111' = TRANSMIT -> TRANSMIT (all open/focused/outward).
export const hexagrams = [
    {
        id: 1,
        pattern: '000000',
        name: 'Observer',
        glyph: null,
        lower: 'MONITOR',
        upper: 'MONITOR',
        coreSense: 'Open attention with nothing in particular to attend to.',
        image: 'You\'re available, but no specific connection is being made right now. The situation is open and isn\'t asking anything of you, and this may continue for a while.',
    },
    {
        id: 2,
        pattern: '000001',
        name: 'Preface',
        glyph: null,
        lower: 'MONITOR',
        upper: 'STANDBY',
        coreSense: 'Open, quiet availability beginning to tilt toward readiness to reach out.',
        image: 'Nothing has called your attention yet, but the orientation is shifting. You\'re not sending anything, not aimed at anyone, but the capacity to reach out is quietly coming online.',
    },
    {
        id: 3,
        pattern: '000010',
        name: 'Sighting',
        glyph: null,
        lower: 'MONITOR',
        upper: 'TUNE',
        coreSense: 'Open, undirected availability narrowing as one specific thing claims attention.',
        image: 'Something has surfaced from the general openness and is worth watching. Nothing has happened yet, but your attention is beginning to settle on one particular person or source.',
    },
    {
        id: 4,
        pattern: '000011',
        name: 'Resolve',
        glyph: null,
        lower: 'MONITOR',
        upper: 'AIM',
        coreSense: 'Quiet availability crystallizing into a specific intention without acting yet.',
        image: 'A direction is forming out of the openness. Nothing has happened yet, but you\'re no longer just available. You\'re aimed at something, holding an intention that hasn\'t moved into action.',
    },
    {
        id: 5,
        pattern: '000100',
        name: 'Influx',
        glyph: null,
        lower: 'MONITOR',
        upper: 'SCAN',
        coreSense: 'Passive availability activating as input arrives from many directions at once.',
        image: 'The quiet has broken and things are coming in from everywhere. Nothing is sorted yet. The value right now is the breadth of what\'s arriving, not any particular piece of it.',
    },
    {
        id: 6,
        pattern: '000101',
        name: 'Emergence',
        glyph: null,
        lower: 'MONITOR',
        upper: 'BROADCAST',
        coreSense: 'Quiet availability tipping into wide outward expression.',
        image: 'Something that was waiting has begun to move outward. You\'re not directing it at anyone in particular, but the stillness is becoming presence, and that presence is going everywhere at once.',
    },
    {
        id: 7,
        pattern: '000110',
        name: 'Arrival',
        glyph: null,
        lower: 'MONITOR',
        upper: 'RECEIVE',
        coreSense: 'General openness finding the one thing it was waiting for.',
        image: 'One person or one thing has claimed your full attention. The wide-open availability is focusing around it now. This is what you were available for, even if you didn\'t know so until this moment.',
    },
    {
        id: 8,
        pattern: '000111',
        name: 'Ignition',
        glyph: null,
        lower: 'MONITOR',
        upper: 'TRANSMIT',
        coreSense: 'Quiet openness becoming full, committed action toward one specific place.',
        image: 'The stillness was real, and so is what breaks it. Something that formed in that open, unhurried space is now moving as a complete act: all of you going to one specific person or place, nothing held back.',
    },
    {
        id: 9,
        pattern: '001000',
        name: 'Fallow',
        glyph: null,
        lower: 'STANDBY',
        upper: 'MONITOR',
        coreSense: 'Readiness to reach out giving way to open, quiet availability.',
        image: 'You have real capacity to put things out into the world, but the push to do that is easing. The situation is shifting toward openness rather than outward action, available to whatever arrives without directing anything.',
    },
    {
        id: 10,
        pattern: '001001',
        name: 'Reserve',
        glyph: null,
        lower: 'STANDBY',
        upper: 'STANDBY',
        coreSense: 'Real capacity to reach out, held quietly and not yet used.',
        image: 'You have genuine ability to put things out into the world and reach many people, but nothing is happening with that right now. The capacity is real and it continues this way, intact and waiting.',
    },
    {
        id: 11,
        pattern: '001010',
        name: 'Bearing',
        glyph: null,
        lower: 'STANDBY',
        upper: 'TUNE',
        coreSense: 'Broad, undirected readiness starting to fix on one particular thing.',
        image: 'Nothing has arrived yet and nothing has been done, but your attention is beginning to settle in one direction. One person or situation is gaining weight without yet having made contact.',
    },
    {
        id: 12,
        pattern: '001011',
        name: 'Draw',
        glyph: null,
        lower: 'STANDBY',
        upper: 'AIM',
        coreSense: 'Unfocused readiness gathering behind one specific intention.',
        image: 'What was available in many directions is pulling together into something more specific. You haven\'t acted yet, but your energy is no longer scattered. It\'s all moving behind one intended direction.',
    },
    {
        id: 13,
        pattern: '001100',
        name: 'Canvass',
        glyph: null,
        lower: 'STANDBY',
        upper: 'SCAN',
        coreSense: 'Readiness to put things out becoming eagerness to take things in.',
        image: 'What was poised to speak is now listening, and not to one person but to many. The whole range of what\'s out there is coming in at once, and that\'s the point right now.',
    },
    {
        id: 14,
        pattern: '001101',
        name: 'Release',
        glyph: null,
        lower: 'STANDBY',
        upper: 'BROADCAST',
        coreSense: 'Held-back outward capacity activating now that there\'s something to say.',
        image: 'The ability to reach people was always there. Now there\'s something to put through it. You\'re going out to a wide audience now, saying something not aimed at any one person but offered to everyone who\'s there.',
    },
    {
        id: 15,
        pattern: '001110',
        name: 'Mooring',
        glyph: null,
        lower: 'STANDBY',
        upper: 'RECEIVE',
        coreSense: 'Scattered readiness settling into deep attention on one specific thing.',
        image: 'Everything you had available is being pulled toward one particular person or situation. What was open in many directions becomes a deep and complete listening. Something specific is claiming all of it.',
    },
    {
        id: 16,
        pattern: '001111',
        name: 'Commission',
        glyph: null,
        lower: 'STANDBY',
        upper: 'TRANSMIT',
        coreSense: 'All the held-back readiness committing at last to one specific place.',
        image: 'Everything that was waiting is now aimed at one specific person or direction. Nothing is scattered or held in reserve anymore. The full weight of what was ready is going there.',
    },
    {
        id: 17,
        pattern: '010000',
        name: 'Aperture',
        glyph: null,
        lower: 'TUNE',
        upper: 'MONITOR',
        coreSense: 'Pointed vigil loosening into wide, unfocused availability.',
        image: 'The specific thing you were watching for hasn\'t come, or something has shifted, and the tight waiting is opening outward. You\'re available again to whatever the situation offers, aimed at nothing in particular.',
    },
    {
        id: 18,
        pattern: '010001',
        name: 'Threshold',
        glyph: null,
        lower: 'TUNE',
        upper: 'STANDBY',
        coreSense: 'Focused inward waiting beginning to tilt toward outward reach.',
        image: 'The pointed attention that was watching one source is starting to turn around. Nothing is going out yet, but the situation is shifting from waiting-to-receive toward readiness-to-reach-out.',
    },
    {
        id: 19,
        pattern: '010010',
        name: 'Vigil',
        glyph: null,
        lower: 'TUNE',
        upper: 'TUNE',
        coreSense: 'Focused waiting holding steady, the expectant attention continuing.',
        image: 'You\'re watching for something from one specific source, and the watching continues. Nothing has arrived, but the attention hasn\'t wavered. The same pointed readiness, sustained through time.',
    },
    {
        id: 20,
        pattern: '010011',
        name: 'Pivot',
        glyph: null,
        lower: 'TUNE',
        upper: 'AIM',
        coreSense: 'Focused waiting on one thing resolving into focused intention toward one thing.',
        image: 'What you were waiting to receive has become something you intend to do. The close focus holds through the turn. The same sharpness that was watching is now aimed outward, at one specific target.',
    },
    {
        id: 21,
        pattern: '010100',
        name: 'Breach',
        glyph: null,
        lower: 'TUNE',
        upper: 'SCAN',
        coreSense: 'Narrow focused vigil broken open by input arriving from many directions.',
        image: 'It wasn\'t what you were waiting for, but the world has answered anyway, from many directions at once. The tight waiting is flooded by a wide rush of incoming things, and the breadth of that is worth paying attention to.',
    },
    {
        id: 22,
        pattern: '010101',
        name: 'Exhale',
        glyph: null,
        lower: 'TUNE',
        upper: 'BROADCAST',
        coreSense: 'Close, inward watching releasing into wide outward expression.',
        image: 'What was held tight and pointed inward is breathing out across a wide field. Nothing aimed at any one person, no single target. The watching opens into something that goes in all directions at once.',
    },
    {
        id: 23,
        pattern: '010110',
        name: 'Answer',
        glyph: null,
        lower: 'TUNE',
        upper: 'RECEIVE',
        coreSense: 'Patient watching met by the thing it was waiting for.',
        image: 'The person or situation you were watching has arrived. What was held open in expectation is now actually receiving. The waiting and the receiving are one continuous state finding its completion.',
    },
    {
        id: 24,
        pattern: '010111',
        name: 'Return',
        glyph: null,
        lower: 'TUNE',
        upper: 'TRANSMIT',
        coreSense: 'Patient watching turning into full, committed action toward one place.',
        image: 'The waiting is over, not abandoned but fulfilled as the energy turns outward. The same focus that was watching one person or situation is now giving everything to one target, fully committed, nothing held back.',
    },
    {
        id: 25,
        pattern: '011000',
        name: 'Prospect',
        glyph: null,
        lower: 'AIM',
        upper: 'MONITOR',
        coreSense: 'Focused intention releasing into wide, unfocused availability.',
        image: 'The aim is loosening without having fired. The sharp intention is giving way to something wider and more open. No particular target, no particular source, just a broad availability to whatever the field offers.',
    },
    {
        id: 26,
        pattern: '011001',
        name: 'Poise',
        glyph: null,
        lower: 'AIM',
        upper: 'STANDBY',
        coreSense: 'One specific intention forming alongside broader, quieter readiness.',
        image: 'You have something aimed at one particular place, and alongside it a wider readiness that hasn\'t been called into use yet. Two kinds of preparation are accumulating at once, neither of them spent.',
    },
    {
        id: 27,
        pattern: '011010',
        name: 'Inversion',
        glyph: null,
        lower: 'AIM',
        upper: 'TUNE',
        coreSense: 'Readiness to act on one thing turning into patient waiting on that same thing.',
        image: 'You were ready to make a move toward one specific person or situation. Now the same sharp focus is turning around, holding still, waiting for something to come from that direction instead.',
    },
    {
        id: 28,
        pattern: '011011',
        name: 'Brace',
        glyph: null,
        lower: 'AIM',
        upper: 'AIM',
        coreSense: 'Held intention continuing, the focused readiness persisting without releasing.',
        image: 'The intention is formed and aimed, and it stays that way. The moment to act hasn\'t come, and the holding is deliberate. One specific target, the full readiness maintained, the decision to wait kept.',
    },
    {
        id: 29,
        pattern: '011100',
        name: 'Survey',
        glyph: null,
        lower: 'AIM',
        upper: 'SCAN',
        coreSense: 'Single intention loosening as information arrives from many directions.',
        image: 'The fixed aim is releasing into something wider. Things are arriving from all directions now, and the situation has shifted from locked-on-one-thing to open-to-everything. There\'s more out there than that one target suggested.',
    },
    {
        id: 30,
        pattern: '011101',
        name: 'Scatter',
        glyph: null,
        lower: 'AIM',
        upper: 'BROADCAST',
        coreSense: 'Focused intention releasing into expression that goes to many at once.',
        image: 'What you had aimed at one specific place is going out more broadly now. It reaches many people at once rather than the single target it was heading for. What was held for one becomes available to many.',
    },
    {
        id: 31,
        pattern: '011110',
        name: 'Yield',
        glyph: null,
        lower: 'AIM',
        upper: 'RECEIVE',
        coreSense: 'Readiness to give something reversing into openness to receive.',
        image: 'The aim is turning around, and the close focus holds through the reversal. What was poised to be given becomes instead an opening to take in. The same sharpness, now facing the other way.',
    },
    {
        id: 32,
        pattern: '011111',
        name: 'Dispatch',
        glyph: null,
        lower: 'AIM',
        upper: 'TRANSMIT',
        coreSense: 'Held intention releasing into full committed action at last.',
        image: 'The readiness has become an act. Everything that was held is going to one specific place with full force, nothing scattered, nothing withheld. This is the direct completion of what was aimed at.',
    },
    {
        id: 33,
        pattern: '100000',
        name: 'Lull',
        glyph: null,
        lower: 'SCAN',
        upper: 'MONITOR',
        coreSense: 'Wide active intake settling into wide passive availability.',
        image: 'The busy gathering is stilling. The breadth stays, but the active pulling-in eases into patient openness. Available to whatever arrives, no longer sweeping and sorting, just present to the field.',
    },
    {
        id: 34,
        pattern: '100001',
        name: 'Crest',
        glyph: null,
        lower: 'SCAN',
        upper: 'STANDBY',
        coreSense: 'Wide active gathering tipping toward readiness to reach many people.',
        image: 'The intake is reaching a turning point. Nothing is going out yet, but the capacity to reach a wide audience is coming alive alongside the gathering. Something is almost ready to share, though it hasn\'t left yet.',
    },
    {
        id: 35,
        pattern: '100010',
        name: 'Catch',
        glyph: null,
        lower: 'SCAN',
        upper: 'TUNE',
        coreSense: 'Wide active intake narrowing as one thing claims the full attention.',
        image: 'One source in the broad reception has become interesting in a way the others haven\'t. The wide sweep is contracting around it. No signal yet, but the searching phase is over and the watching has begun.',
    },
    {
        id: 36,
        pattern: '100011',
        name: 'Elect',
        glyph: null,
        lower: 'SCAN',
        upper: 'AIM',
        coreSense: 'Wide gathering resolving into one chosen direction.',
        image: 'Out of everything you\'ve been taking in, one thing is being selected and committed to. The research is done, the choice has been made, and the aim is set. Everything narrows to that one direction now.',
    },
    {
        id: 37,
        pattern: '100100',
        name: 'Sweep',
        glyph: null,
        lower: 'SCAN',
        upper: 'SCAN',
        coreSense: 'Wide active intake sustaining itself, the broad gathering continuing.',
        image: 'Input keeps arriving from the whole field and the situation stays that way. Wide open, nothing filtered, nothing committed to yet. The value is in the accumulation. Nothing needs to narrow right now.',
    },
    {
        id: 38,
        pattern: '100101',
        name: 'Relay',
        glyph: null,
        lower: 'SCAN',
        upper: 'BROADCAST',
        coreSense: 'Wide gathering turning into wide sharing.',
        image: 'What was coming in from many sources is now going out to many people. You\'re a relay: gathered from everywhere, passed on to everyone. Nothing collapsed into one narrow channel, the breadth holds in both directions.',
    },
    {
        id: 39,
        pattern: '100110',
        name: 'Landing',
        glyph: null,
        lower: 'SCAN',
        upper: 'RECEIVE',
        coreSense: 'Restless wide gathering settling into deep listening to one thing.',
        image: 'The broad searching is settling at last on one person or source. The restless gathering becomes deep and still as your attention narrows to one thing coming in fully. The searching is over. The listening is beginning.',
    },
    {
        id: 40,
        pattern: '100111',
        name: 'Distill',
        glyph: null,
        lower: 'SCAN',
        upper: 'TRANSMIT',
        coreSense: 'Wide gathering processed down into one thing to say to one person.',
        image: 'Everything you\'ve been taking in is being converted into one specific act toward one specific place. The long intake phase is ending. What\'s left is the one thing to say, said once, to the right person.',
    },
    {
        id: 41,
        pattern: '101000',
        name: 'Echo',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'MONITOR',
        coreSense: 'Busy outward sending settling into quiet, open availability.',
        image: 'The sending is stilling. The wide reach stays, but the active push outward eases. What was going out is now simply present to whatever comes back, open and unhurried, not aimed at anything particular.',
    },
    {
        id: 42,
        pattern: '101001',
        name: 'Recess',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'STANDBY',
        coreSense: 'Active wide sending pulling back into quiet reserve.',
        image: 'The sending is stopping, but the ability to reach people isn\'t going away. The wide audience is still there, the capacity to reach them is still live. Nothing is going out right now. The pause is real and so is the reach.',
    },
    {
        id: 43,
        pattern: '101010',
        name: 'Gather',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'TUNE',
        coreSense: 'Wide outward sending contracting into close watching of one particular thing.',
        image: 'The broad sending is narrowing and turning inward. Something in everything you\'ve been putting out is now worth watching closely, and the attention is pulling toward it. The wide expression is becoming a focused vigil.',
    },
    {
        id: 44,
        pattern: '101011',
        name: 'Tether',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'AIM',
        coreSense: 'Effort spread across many people gathering into one specific intention.',
        image: 'What was going out to many is being drawn toward one place. Out of everyone you\'ve been putting things out to, one person or direction has named itself as the destination, and the intention is now pointed there.',
    },
    {
        id: 45,
        pattern: '101100',
        name: 'Upturn',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'SCAN',
        coreSense: 'Wide sending reversing into wide receiving.',
        image: 'The direction flips while the breadth holds. What was going out to many is now opening to take in from many. Everything out there starts arriving at once, and the wide reach that was putting things out becomes a wide intake.',
    },
    {
        id: 46,
        pattern: '101101',
        name: 'Open Channel',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'BROADCAST',
        coreSense: 'Wide active sending continuing, no narrowing, no pulling back.',
        image: 'You\'re putting things out into the world for many people at once, and that continues. Nothing is asking you to narrow it down or stop. The wide reach stays wide and keeps going.',
    },
    {
        id: 47,
        pattern: '101110',
        name: 'Attend',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'RECEIVE',
        coreSense: 'Wide sending narrowing and reversing into deep listening to one person.',
        image: 'One specific voice is rising above the wide outward push. The broad sending contracts and turns around until the attention is fully open to one person. The one who was speaking to a crowd stops to listen to one person in it.',
    },
    {
        id: 48,
        pattern: '101111',
        name: 'Forge',
        glyph: null,
        lower: 'BROADCAST',
        upper: 'TRANSMIT',
        coreSense: 'Spread effort gathering into one focused commitment.',
        image: 'You\'ve been doing many things at once, sharing yourself widely. Now your attention is gathering into one specific direction, and whatever comes of this will have all of you behind it.',
    },
    {
        id: 49,
        pattern: '110000',
        name: 'Soften',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'MONITOR',
        coreSense: 'Deep committed listening easing into wide, open availability.',
        image: 'The close listening is opening out. The person or thing that held all your attention is releasing it into something more diffuse. You\'re available to whatever comes now, no longer held to one source.',
    },
    {
        id: 50,
        pattern: '110001',
        name: 'Surface',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'STANDBY',
        coreSense: 'Deep listening starting to look outward toward a wider audience.',
        image: 'The deep listening is starting to look up. The capacity to reach many people is coming alive alongside it, held but not yet used. What you\'ve been taking in hasn\'t gone out yet, but that possibility is waking.',
    },
    {
        id: 51,
        pattern: '110010',
        name: 'Linger',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'TUNE',
        coreSense: 'Deep active listening becoming patient expectation as things go quiet.',
        image: 'Something was arriving fully, and now it has gone quiet. The attention stays pointed at the same source, expecting more. The conversation has paused but not ended, and you stay with it, still facing the same direction.',
    },
    {
        id: 52,
        pattern: '110011',
        name: 'Turning',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'AIM',
        coreSense: 'Deep listening pivoting into a specific intention to act.',
        image: 'What you\'ve taken in is becoming something to give. The deep reception is becoming a held intention. The same sharpness, pointed the other way now. The listening is ending and the response is about to begin.',
    },
    {
        id: 53,
        pattern: '110100',
        name: 'Widen',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'SCAN',
        coreSense: 'Deep focused reception opening into wide active intake.',
        image: 'The single source is giving way to many. The close attention is expanding outward, pulling in from across the field. What required full focus on one thing is becoming a wide and busy gathering.',
    },
    {
        id: 54,
        pattern: '110101',
        name: 'Offering',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'BROADCAST',
        coreSense: 'Deep listening to one person reversing into wide expression to many.',
        image: 'What came in through a close, specific exchange is going out broadly now. The deep listening is becoming wide expression. Nothing held back, nothing aimed at one person, it goes out to whoever is there.',
    },
    {
        id: 55,
        pattern: '110110',
        name: 'Immersion',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'RECEIVE',
        coreSense: 'Deep focused reception holding steady, the close listening sustained.',
        image: 'The connection to one source stays fully open and keeps going. One person, one work, one experience. Nothing narrowing further, nothing widening. The same depth of attention that was present continues to be present.',
    },
    {
        id: 56,
        pattern: '110111',
        name: 'Passage',
        glyph: null,
        lower: 'RECEIVE',
        upper: 'TRANSMIT',
        coreSense: 'Deep listening becoming full committed action, what was taken in now given out.',
        image: 'The deep intake has become a deep output. The same total commitment, the same close focus on one person, only the direction reversed. Someone who has listened fully now speaks fully in return.',
    },
    {
        id: 57,
        pattern: '111000',
        name: 'Repose',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'MONITOR',
        coreSense: 'Focused committed effort releasing into wide, open stillness.',
        image: 'The concentrated effort is easing, not switching to another target but opening out. What was fully committed to one place is releasing into something diffuse and still. Available to whatever arrives, just present and unhurried.',
    },
    {
        id: 58,
        pattern: '111001',
        name: 'Interval',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'STANDBY',
        coreSense: 'Concentrated effort pausing while the capacity to reach out stays alive.',
        image: 'The specific work is stopping, but your ability to reach people isn\'t going away. What was entirely focused on one person or project becomes broad and quiet, held in reserve while the active part rests.',
    },
    {
        id: 59,
        pattern: '111010',
        name: 'Spend',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'TUNE',
        coreSense: 'Full committed effort completing and turning into patient waiting.',
        image: 'You\'ve said everything you had to say to one person or place, and now you go quiet, listening for what comes back. The same close focus stays intact. Only the direction has reversed.',
    },
    {
        id: 60,
        pattern: '111011',
        name: 'Sustain',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'AIM',
        coreSense: 'Active work pausing while the commitment to one direction stays in place.',
        image: 'The active work has paused, but the direction stays fixed. You\'re still aimed at the same person or place, just not doing anything right now. The commitment is on hold, not over.',
    },
    {
        id: 61,
        pattern: '111100',
        name: 'Harvest',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'SCAN',
        coreSense: 'Concentrated outward effort completing and opening wide to take in.',
        image: 'The focused giving is over for now, and you\'re opening wide to take in from everywhere. What was fully committed to one place becomes a broad, open receiving, replenished from the whole field.',
    },
    {
        id: 62,
        pattern: '111101',
        name: 'Diffuse',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'BROADCAST',
        coreSense: 'Effort given entirely to one person spreading out to many.',
        image: 'What was going entirely to one person is spreading out to many. The close, committed focus opens wide. What was held for one becomes available to everyone, the direction staying outward while the aim releases.',
    },
    {
        id: 63,
        pattern: '111110',
        name: 'Exchange',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'RECEIVE',
        coreSense: 'Full commitment to one person reversing into full reception from that same person.',
        image: 'The direction reverses while the close focus holds. The same total commitment, the same particular person or place, but now you\'re receiving rather than giving. The energy is coming in fully from that one source.',
    },
    {
        id: 64,
        pattern: '111111',
        name: 'Full Tilt',
        glyph: null,
        lower: 'TRANSMIT',
        upper: 'TRANSMIT',
        coreSense: 'Full commitment to one person or project sustaining itself.',
        image: 'One person, one direction, all of you going there, nothing scattered, and this continues. The situation isn\'t building to a peak or about to change. This is what it looks like when full commitment is the ongoing state.',
    },
]
