// The 64 channel-trajectory entries. Each describes one hexagram (lower trigram = present,
// upper trigram = emerging).
//
// Pattern string reads bottom-to-top: char 1 = line 1 (bottom of lower trigram),
// char 6 = line 6 (top of upper trigram).
// ID = (pattern string interpreted as binary number, leftmost char as MSB) + 1.
// This means the lower trigram is the high 3 bits and the upper trigram is the low 3 bits,
// so IDs cluster by lower trigram (8 IDs per lower trigram value).
//
// Hexagram 1 = pattern '000000' = MONITOR -> MONITOR (all closed/distributed/inward).
// Hexagram 64 = pattern '111111' = TRANSMIT -> TRANSMIT (all open/focused/outward).
export const hexagrams = [
    {
        id: 1,
        pattern: '000000',
        name: 'Stillwater',
        glyph: null,
        lower: 'MONITOR',
        upper: 'MONITOR',
        coreSense: 'Wide availability persisting - open and quiet, with nothing arriving and nothing changing.',
        image: 'The channel is open and has been open for a while. Nothing is arriving. No specific source has claimed your attention, no signal has broken the quiet. This isn\'t restlessness - the availability itself is stable, held without strain. A harbor in flat weather: the water is real, the depth is real, the readiness is real. No ships are coming in. You\'re not waiting for anything particular; you\'re simply present to the field. The situation isn\'t moving. This is what it is right now - an open, quiet, unhurried space that is its own kind of fullness.',
    },
    {
        id: 2,
        pattern: '000001',
        name: 'Preface',
        glyph: null,
        lower: 'MONITOR',
        upper: 'STANDBY',
        coreSense: 'Open quiet availability beginning to orient toward expression - receptivity tilting into readiness to send.',
        image: 'You\'ve been open to whatever came - no particular agenda, no specific source filling you. Something in that wide, patient receiving has started to shift. The orientation is turning. You\'re not sending yet, and there\'s no message formed, but the posture is changing from available-to-receive to available-to-reach-out. A stage being set before anyone knows what the performance will be. The infrastructure of expression is coming online - the network, the reach, the capacity - held quietly, pointing outward without yet having anything to say.',
    },
    {
        id: 3,
        pattern: '000010',
        name: 'Sighting',
        glyph: null,
        lower: 'MONITOR',
        upper: 'TUNE',
        coreSense: 'Wide undirected availability narrowing to a pointed vigil - something specific worth attending to has emerged from the quiet.',
        image: 'The wide, open listening has caught something. Out of the general availability - no focus, no target, just readiness - one frequency has come forward. You haven\'t heard it yet; nothing has arrived. But the attention is narrowing now, drawn toward one specific source. A naturalist pausing mid-walk, suddenly alert to a particular corner of the forest. The scan is over. The tuning has begun. You\'re holding the channel open in one direction now, configured to catch whatever this particular source will send.',
    },
    {
        id: 4,
        pattern: '000011',
        name: 'Resolve',
        glyph: null,
        lower: 'MONITOR',
        upper: 'AIM',
        coreSense: 'Open, objectless availability crystallizing into a specific directed intention - quiet becomes purpose.',
        image: 'Something has formed in the silence. The wide open availability - receiving nothing, aimed at nothing - has been a kind of gestation. Now a direction is emerging: not a signal sent, but an intention taking shape, an antenna being pointed at one specific target. The nocked arrow hasn\'t left the bow yet. The intention is real and aimed at something particular, but no action has been taken. What was empty receiving is becoming focused, directed, latent purpose - the quiet that precedes a specific move.',
    },
    {
        id: 5,
        pattern: '000100',
        name: 'Influx',
        glyph: null,
        lower: 'MONITOR',
        upper: 'SCAN',
        coreSense: 'Passive open availability activating into wide intake - the quiet starts filling from many directions.',
        image: 'The channel was open and empty - available but not receiving, waiting on nothing in particular. Now input is arriving, and it\'s arriving from everywhere at once. The availability that was passive has become active: things are coming in, signals from many directions, a rush of data that hasn\'t been sorted yet. Reading the room after the room has finally started talking. Nothing is being filtered, nothing committed to - the value right now is in the breadth of what\'s arriving. The wide aperture that was held open for its own sake has found what it was configured for.',
    },
    {
        id: 6,
        pattern: '000101',
        name: 'Emergence',
        glyph: null,
        lower: 'MONITOR',
        upper: 'BROADCAST',
        coreSense: 'Wide empty receptivity reversing into wide active sending - the quiet turns outward.',
        image: 'The open availability has been entirely inward - wide, unfocused, taking nothing in, asking nothing of anyone. Now the direction is reversing. The same distributed, wide-open posture is becoming outward: signals going out across a broad field, energy spreading to many receivers at once. Not concentrated, not aimed - the dispersal is the point. Something that lived in the space of patient receiving has found its way out into the world, scattering in multiple directions at once. The silent hospitality becomes a broadcast.',
    },
    {
        id: 7,
        pattern: '000110',
        name: 'Arrival',
        glyph: null,
        lower: 'MONITOR',
        upper: 'RECEIVE',
        coreSense: 'Diffuse open availability meeting a specific guest - the wide hospitality finds its particular recipient.',
        image: 'The channel has been open without object - general availability, wide and unfocused, the hospitality without guests. Now a guest has arrived. Not many, not a flood of input from all directions - one source, one signal, requiring full attention. The wide aperture narrows to a single point of deep contact. Someone has walked into the open space and the openness is now entirely theirs. This is what the readiness was for, even if you didn\'t know who it was readiness for. The availability has found its focus.',
    },
    {
        id: 8,
        pattern: '000111',
        name: 'Ignition',
        glyph: null,
        lower: 'MONITOR',
        upper: 'TRANSMIT',
        coreSense: 'Dormant open availability breaking into concentrated directed action - the deepest quiet becomes the fullest signal.',
        image: 'Everything was quiet. The channel was open in the most diffuse, least directed way - available to anything, holding nothing, aimed at nothing. Now the direction has reversed completely and the concentration has reached maximum: one target, one signal, all active energy going there. Nothing scattered, nothing held back. Whatever formed in the wide empty space has resolved into the clearest possible output - focused, outward, fully committed. The silence was real; so is what breaks it. A long patient openness has become an entirely specific act.',
    },
    {
        id: 9,
        pattern: '001000',
        name: 'Fallow',
        glyph: null,
        lower: 'STANDBY',
        upper: 'MONITOR',
        coreSense: 'Wide latent reach turning inward - the silent transmitter opens instead to whatever comes.',
        image: 'The capacity was there, pointed outward - a live transmitter with nothing to send, a network with no message queued. Now the orientation is shifting. The outward reach isn\'t firing; instead the channel is turning around, opening wide to receive from anywhere. Not a specific source, not a focused attention - just a broad inward availability replacing the broad outward reserve. A field left unplanted to recover: the infrastructure stays real, the reach stays real, but right now nothing is going out. What held itself ready to broadcast is opening itself to be filled instead.',
    },
    {
        id: 10,
        pattern: '001001',
        name: 'Reserve',
        glyph: null,
        lower: 'STANDBY',
        upper: 'STANDBY',
        coreSense: 'Wide latent reach holding steady - the capacity continues in reserve, neither activating nor releasing.',
        image: 'The transmitter is live. The reach is real. Nothing is being sent. And this continues - not as a problem, not as a pause before something else, but as a state that is sustaining itself. The stage stays set without a performance beginning. The network remains connected without traffic. There\'s no signal, no message, no target - just the maintained readiness of wide outward capacity held in reserve. A lighthouse that isn\'t needed tonight but keeps its lamp trimmed anyway. The silence isn\'t empty; it\'s kept. The capacity isn\'t idle; it\'s held. This is what ongoing reserve looks like.',
    },
    {
        id: 11,
        pattern: '001010',
        name: 'Bearing',
        glyph: null,
        lower: 'STANDBY',
        upper: 'TUNE',
        coreSense: 'Wide diffuse reserve beginning to orient toward one specific source - the latent reach finds a direction to attend.',
        image: 'The channel has been silent and spread wide - reach available in every direction, nothing going out, no particular thing drawing attention. Something has started to shift. Not a signal yet, not a message forming - but the open awareness is beginning to narrow, orienting toward one specific source. A listener in a noisy room who goes still because something in one corner has become interesting. The wide quiet reserve hasn\'t fired; it\'s starting to focus its attention on one particular frequency. Where everything was undirected, now one direction has weight. The capacity is beginning to listen.',
    },
    {
        id: 12,
        pattern: '001011',
        name: 'Draw',
        glyph: null,
        lower: 'STANDBY',
        upper: 'AIM',
        coreSense: 'Wide diffuse reserve collapsing into a single pointed intention - broad capacity sharpening toward one target.',
        image: 'The reach was wide and silent - a transmitter with no message, capacity spread across many directions without any of them claiming it. Something is pulling it together now. The distribution is collapsing inward to a point: one target, one direction, the antenna swinging to align on something specific. No signal is going yet - the arrow hasn\'t left the bow. But where the capacity was scattered and undirected, it\'s now drawn back and aimed. The whole diffuse reserve is behind this one intended direction. The wide silence has become a specific readiness.',
    },
    {
        id: 13,
        pattern: '001100',
        name: 'Canvass',
        glyph: null,
        lower: 'STANDBY',
        upper: 'SCAN',
        coreSense: 'Silent outward reserve reversing into wide active intake - the held capacity opens to signal arriving from many directions.',
        image: 'The channel was live but quiet, pointed outward with nothing to send. Now the direction has flipped: instead of a transmitter waiting for a message, a wide receiver is pulling in from everywhere at once. The shift isn\'t from quiet to noise - it\'s from a particular kind of readiness to its mirror image. What was ready to speak is now ready to listen, and not to one thing but to many. Data arriving from multiple directions, the field talking back. Reading the room after holding still long enough for people to start talking. The wide reach that was reserved for sending is now drawing in.',
    },
    {
        id: 14,
        pattern: '001101',
        name: 'Release',
        glyph: null,
        lower: 'STANDBY',
        upper: 'BROADCAST',
        coreSense: 'Latent outward capacity activating into wide sending - the reserve finds its signal and goes out.',
        image: 'The transmitter was live. The reach was real. There was just nothing to send. Now there is. The capacity that was held in reserve - the platform, the network, the wide potential audience - is being used. Not narrowed to one target, not concentrated into a single message: the signal is going out across the whole field at once, spreading to many receivers. The same broad reach that was silent is now active. A broadcast that finally begins after the equipment has been on and waiting. The stage has been set long enough; the performance starts. What was held is released into the wide open.',
    },
    {
        id: 15,
        pattern: '001110',
        name: 'Mooring',
        glyph: null,
        lower: 'STANDBY',
        upper: 'RECEIVE',
        coreSense: 'Wide diffuse reserve narrowing and reversing into deep focused reception - the broad silence settles into one specific source.',
        image: 'The reach was wide and going nowhere - a live transmitter with no message, distributed in all directions without landing anywhere. Something is pulling it to a point and turning it around. The broad outward capacity is becoming focused inward reception: not many sources, not a wide sweep, but one thing that now has full attention. A boat that has been drifting in open water, suddenly finding the dock it didn\'t know it was heading for. The reserve doesn\'t activate outward - it anchors inward, to one specific source that is now claiming everything the channel has. The wide silence becomes a deep, specific listening.',
    },
    {
        id: 16,
        pattern: '001111',
        name: 'Commission',
        glyph: null,
        lower: 'STANDBY',
        upper: 'TRANSMIT',
        coreSense: 'Wide latent reserve sharpening into concentrated directed action - all held capacity deployed toward one target.',
        image: 'The transmitter was live and silent, reach held wide, capacity distributed and unspent. Now the whole reserve is being collected and aimed at one specific place. Nothing scattered: the distributed capacity is collapsing into a single focused line from you to one target. Nothing held back: everything that was in reserve is going there. The breadth of what STANDBY held doesn\'t scatter into broadcast - it narrows completely, sharpens to a point, and fires with the full force of everything that was waiting. A long unreleased capacity converted entirely into a single, concentrated act.',
    },
]
