// The 8 channel-state entries. Each describes one trigram pattern.
// Patterns read bottom-to-top: bottom = open/closed, middle = focused/distributed,
// top = outward/inward. (1 = open/focused/outward; 0 = closed/distributed/inward.)
export const trigrams = [
    {
        id: 1,
        pattern: '000',
        name: 'MONITOR',
        glyph: '☷',
        coreSense: 'Receiver active, nothing arriving - available to whatever comes.',
        description: 'The channel is open in a general sense - no specific source is filling it. You\'re available, attentive, ready to receive from any direction. Nothing is arriving right now. This is hospitality without guests: the space is prepared, the attention is real, but no signal has come in yet.\n\nMONITOR is the most diffuse and receptive posture. It holds the widest aperture. Nothing is focused, nothing is aimed, nothing is flowing - but the readiness itself is a kind of presence. A hollow waiting to be filled, attention without object.',
        range: {
            innerLife: 'A general openness, not focused on anything specific.',
            relationships: 'Available to friends, but no one has called.',
            work: 'Capacity for input you haven\'t received.',
            body: 'Resting state, no sensory focus.',
            world: 'Open civic space, no event happening.',
        },
        inCombination: 'Brings wide, unfocused receptivity - the present channel is taking in everything and nothing in particular.',
    },
    {
        id: 2,
        pattern: '001',
        name: 'STANDBY',
        glyph: '☶',
        coreSense: 'Transmitter live, no message queued - broad reach held in reserve.',
        description: 'The channel has wide reach - a platform, an audience, a network - but nothing is being sent. The transmitter is live. The stage is set. No performance is happening. This is reserved capacity: you have the means to broadcast widely, but you\'re currently silent.\n\nSTANDBY isn\'t absence. The infrastructure is real. A beacon unlit still has the tower, still has the power. What\'s missing is the message, or the moment to send it.',
        range: {
            innerLife: 'A wide-ranging interest currently quiet.',
            relationships: 'A network of acquaintances you\'re not engaging right now.',
            work: 'Public-facing tools and reach you have but aren\'t using.',
            body: 'General energy not directed anywhere.',
            world: 'A broad influence currently dormant.',
        },
        inCombination: 'Brings latent reach - distributed outward capacity held in reserve, waiting for a message.',
    },
    {
        id: 3,
        pattern: '010',
        name: 'TUNE',
        glyph: '☵',
        coreSense: 'Tuned to one frequency, no signal arriving yet - expectant, waiting.',
        description: 'The channel is tuned to a specific source. The attention is real and pointed. But the signal hasn\'t come in yet. This is vigil: you\'re holding a particular frequency open, watching for one specific thing to arrive. Not passive - the attention takes effort - but not yet receiving.\n\nTUNE is the latent pair to RECEIVE. Both are focused inward; TUNE is the same posture before anything arrives. The waiting has a target.',
        range: {
            innerLife: 'Waiting for an answer to surface.',
            relationships: 'Waiting for a response from someone specific.',
            work: 'Awaiting feedback on submitted work.',
            body: 'Sensing for a specific signal.',
            world: 'Watching for one event to happen.',
        },
        inCombination: 'Brings focused, pointed waiting - the present channel is held on one source, expectant but not yet receiving.',
    },
    {
        id: 4,
        pattern: '011',
        name: 'AIM',
        glyph: '☴',
        coreSense: 'Antenna pointed at one target, no signal sent - intention held, not yet enacted.',
        description: 'The channel exists and is aimed at a specific place. Ready to fire. But it isn\'t carrying anything right now. This is the nocked arrow, the vow not yet spoken, the plan fully formed and not yet begun. The direction is clear; the action is held.\n\nAIM is the latent pair to TRANSMIT. Both are focused outward; AIM is the same posture before the signal goes. The intention has a target.',
        range: {
            innerLife: 'A goal you\'ve set but aren\'t acting on yet.',
            relationships: 'A confession you\'re holding back; a connection you intend to make.',
            work: 'A project on the back burner; a planned launch.',
            body: 'Held tension awaiting release.',
            world: 'An action being prepared; a pending decision.',
        },
        inCombination: 'Brings focused, pointed intention - the present channel is aimed but not yet firing.',
    },
    {
        id: 5,
        pattern: '100',
        name: 'SCAN',
        glyph: '☳',
        coreSense: 'Sweeping the spectrum, sampling many sources - wide intake.',
        description: 'The channel is active and taking in signal from many directions at once. You\'re reading the room, gathering data, sweeping across the field. The connection is real - things are actually arriving - but spread widely rather than drawn from any single source.\n\nSCAN is intake at scale. Nothing is filtered out yet, nothing is committed to. The value is in the breadth: you see what\'s out there before deciding where to focus.',
        range: {
            innerLife: 'Brainstorming, taking in many possibilities.',
            relationships: 'Listening to a group, reading many people.',
            work: 'Research, intake, gathering data from many sources.',
            body: 'Sensing the field, taking in environmental information.',
            world: 'Surveying public mood, gathering information.',
        },
        inCombination: 'Brings wide, active reception - the present channel is pulling in from everywhere, not yet sorted.',
    },
    {
        id: 6,
        pattern: '101',
        name: 'BROADCAST',
        glyph: '☲',
        coreSense: 'Sending widely to many receivers - energy spread outward.',
        description: 'The channel is active and sending outward to many receivers at once. A crowd, a public, a network. The connection is real but spread thin per recipient - each one gets a fraction of what a focused one-to-one channel would carry. Publication, performance, scattered seed.\n\nBROADCAST is the most outward and diffuse active state. It requires a certain release - you send without knowing exactly who receives, without receiving much back. The signal goes out; the field catches what it catches.',
        range: {
            innerLife: 'An idea you\'re trying out in many directions.',
            relationships: 'Maintaining many connections at once.',
            work: 'A widely-shared project, public-facing communication.',
            body: 'General energy radiating outward.',
            world: 'A public statement, art released into the world.',
        },
        inCombination: 'Brings wide, active sending - the present channel is transmitting to many, diffuse and outward.',
    },
    {
        id: 7,
        pattern: '110',
        name: 'RECEIVE',
        glyph: '☱',
        coreSense: 'Taking in one signal from one source - deep, focused reception.',
        description: 'The channel is active, focused on a single source, with energy moving in toward you. Deep listening. Careful watching. Sustained attention received rather than given. One person, one text, one experience - and you are fully open to it.\n\nRECEIVE is the complement to TRANSMIT. The same concentrated, point-to-point quality, but the direction is reversed. Where TRANSMIT pours out, RECEIVE takes in - and taking in fully requires as much commitment as giving.',
        range: {
            innerLife: 'Concentrated attention on one image or feeling.',
            relationships: 'Listening fully to one person.',
            work: 'Deep apprenticeship to one teacher or text.',
            body: 'Receiving care or healing from one source.',
            world: 'Witnessing one event with full attention.',
        },
        inCombination: 'Brings focused, deep reception - the present channel is fully open to one source.',
    },
    {
        id: 8,
        pattern: '111',
        name: 'TRANSMIT',
        glyph: '☰',
        coreSense: 'Sending one signal to one receiver - concentrated outward energy.',
        description: 'The channel is active, pointed at a single target, with energy moving out from you. This is devoted work, sustained giving, the focused offering. One person, one project, one direction - and all your active energy is going there.\n\nTRANSMIT is the fullest expression of directed action. Nothing is scattered. Nothing is held back. The channel is open, the connection is one-to-one, and the flow is outward. What you have is going where it\'s aimed.',
        range: {
            innerLife: 'Putting all reflective attention on one question.',
            relationships: 'Dedicated attention given fully to one person.',
            work: 'A project that has all your active hours.',
            body: 'Sustained physical effort directed at one task.',
            world: 'A campaign, a sustained advocacy.',
        },
        inCombination: 'Brings concentrated, focused sending - the present channel is fully committed outward to one target.',
    },
]
