// The 8 channel-state entries. Each describes one trigram pattern.
// Patterns read bottom-to-top: bottom = open/closed, middle = focused/distributed,
// top = outward/inward. (1 = open/focused/outward; 0 = closed/distributed/inward.)
export const trigrams = [
    {
        id: 1,
        pattern: '000',
        name: 'MONITOR',
        glyph: '☷',
        coreSense: 'Wide open availability with nothing arriving.',
        description: 'You\'re receptive to whatever might come, but nothing has come in yet. The attention is real and broad, not aimed at anything specific. Hospitality without guests: the space is prepared, the openness is genuine, and nothing is filling it right now.',
        range: {
            innerLife: 'A general openness, not focused on anything specific.',
            relationships: 'Available to friends, but no one has called.',
            work: 'Capacity for input you haven\'t received.',
            body: 'Resting state, no sensory focus.',
            world: 'Open civic space, no event happening.',
        },
        inCombination: 'Brings wide, unfocused receptivity to a reading - open to whatever might come.',
    },
    {
        id: 2,
        pattern: '001',
        name: 'STANDBY',
        glyph: '☶',
        coreSense: 'Broad reach held ready, nothing being sent.',
        description: 'You have the platform, the network, the capacity to reach many people - but nothing is going out right now. The transmitter is live, the stage is set, no performance is happening. Reserved capacity: the means to broadcast widely, currently silent.',
        range: {
            innerLife: 'A wide-ranging interest currently quiet.',
            relationships: 'A network of acquaintances you\'re not engaging right now.',
            work: 'Public-facing tools and reach you have but aren\'t using.',
            body: 'General energy not directed anywhere.',
            world: 'A broad influence currently dormant.',
        },
        inCombination: 'Brings latent reach - distributed outward capacity held in reserve, waiting for a message.',
    },
    {
        id: 3,
        pattern: '010',
        name: 'TUNE',
        glyph: '☵',
        coreSense: 'Focused on one source, waiting for a signal that hasn\'t come.',
        description: 'Your attention is pointed at something specific, and you\'re holding that focus. But nothing has arrived yet. This is vigil: watching for one particular thing, maintaining a real and specific attention, even in the absence of anything to receive.',
        range: {
            innerLife: 'Waiting for an answer to surface.',
            relationships: 'Waiting for a response from someone specific.',
            work: 'Awaiting feedback on submitted work.',
            body: 'Sensing for a specific signal.',
            world: 'Watching for one event to happen.',
        },
        inCombination: 'Brings focused, pointed waiting - attention held on one source, expectant but not yet receiving.',
    },
    {
        id: 4,
        pattern: '011',
        name: 'AIM',
        glyph: '☴',
        coreSense: 'Intention formed and held toward one target, not yet acted on.',
        description: 'The direction is clear and the energy is gathered, but nothing has been sent yet. The nocked arrow, the plan fully formed, the vow not yet spoken. The intention is real and specific; the action is still held.',
        range: {
            innerLife: 'A goal you\'ve set but aren\'t acting on yet.',
            relationships: 'A confession you\'re holding back, a connection you intend to make.',
            work: 'A project on the back burner, a planned launch.',
            body: 'Held tension awaiting release.',
            world: 'An action being prepared, a pending decision.',
        },
        inCombination: 'Brings focused, pointed intention - aimed at one target but not yet firing.',
    },
    {
        id: 5,
        pattern: '100',
        name: 'SCAN',
        glyph: '☳',
        coreSense: 'Active reception spread across many sources at once.',
        description: 'You\'re taking in signal from many directions at the same time. Reading the room, gathering data, sweeping across the field. Things are actually arriving, but from everywhere rather than one place. Nothing is filtered out yet, nothing committed to. The value is the breadth.',
        range: {
            innerLife: 'Brainstorming, taking in many possibilities.',
            relationships: 'Listening to a group, reading many people.',
            work: 'Research, intake, gathering data from many sources.',
            body: 'Sensing the field, taking in environmental information.',
            world: 'Surveying public mood, gathering information.',
        },
        inCombination: 'Brings wide, active reception - pulling in from everywhere, not yet sorted.',
    },
    {
        id: 6,
        pattern: '101',
        name: 'BROADCAST',
        glyph: '☲',
        coreSense: 'Active sending spread across many receivers at once.',
        description: 'You\'re sending outward to many people at the same time. Publication, performance, scattered seed. The connection is real but diffuse - each person gets a fraction of what a one-to-one conversation would carry. You send without knowing exactly who receives, without getting much back.',
        range: {
            innerLife: 'An idea you\'re trying out in many directions.',
            relationships: 'Maintaining many connections at once.',
            work: 'A widely-shared project, public-facing communication.',
            body: 'General energy radiating outward.',
            world: 'A public statement, art released into the world.',
        },
        inCombination: 'Brings wide, active sending - transmitting to many, diffuse and outward.',
    },
    {
        id: 7,
        pattern: '110',
        name: 'RECEIVE',
        glyph: '☱',
        coreSense: 'Full, focused attention given to one source.',
        description: 'One person, one text, one experience is claiming your complete attention, and you\'re open to it. Deep listening, careful watching. Taking in fully requires as much commitment as giving fully. The connection is one-to-one and the direction is inward.',
        range: {
            innerLife: 'Concentrated attention on one image or feeling.',
            relationships: 'Listening fully to one person.',
            work: 'Deep apprenticeship to one teacher or text.',
            body: 'Receiving care or healing from one source.',
            world: 'Witnessing one event with full attention.',
        },
        inCombination: 'Brings focused, deep reception - fully open to one source.',
    },
    {
        id: 8,
        pattern: '111',
        name: 'TRANSMIT',
        glyph: '☰',
        coreSense: 'All your active energy going to one specific place.',
        description: 'One person, one project, one direction, and you\'re committed there. Nothing is scattered, nothing held back. This is the posture of devoted work and sustained giving. The connection is one-to-one, the flow is outward, and what you have is going where it\'s aimed.',
        range: {
            innerLife: 'Putting all reflective attention on one question.',
            relationships: 'Dedicated attention given fully to one person.',
            work: 'A project that has all your active hours.',
            body: 'Sustained physical effort directed at one task.',
            world: 'A campaign, a sustained advocacy.',
        },
        inCombination: 'Brings concentrated, focused sending - fully committed outward to one target.',
    },
]
